### ISSUE TITLE
Rokid眼镜连接手机方案

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#100]
1、离线语音指令有没有连续数字指令的api
2、sdk是否内置了拍摄照片以及拍摄视频的api

**Comment by lanyuqingri** [comment]
1、离线语音指令有没有连续数字指令的api
-------暂时没有，需要一个一个设置进去
2、sdk是否内置了拍摄照片以及拍摄视频的api
---------目前有在规划开放拍照 & 拍摄视频的api接口以及相关文档，如果您这边项目比较赶，建议可以先使用preview数据做相应的数据处理。

**Comment by kaojin-alt** [comment]
使眼镜拍摄的视频内容在眼镜上呈现，只能在一个Presentation呈现吗？
如果我想在多个Presentation呈现，或者说哪个Presentation显示就再哪个Presentation呈现，怎么解决

**Comment by lanyuqingri** [comment]
Presentation 是android 提供的一套分屏异显的展示方案，本质是Dialog，而且同时只会存在一个Presentation实例，因此如果程序中设计了多个Presentation的话，需要在不同的Presentation里边实现预览画面的展示。

**Comment by kaojin-alt** [comment]
Rokid眼镜连接手机 implementation 'com.rokid.glass:ui:1.5.6' 这个包还能正常使用吗

**Comment by sunchaonew** [comment]
> glass:ui
com.rokid.glass:ui 这个包是在glass端使用的，眼镜连接手机是不支持的
