### ISSUE TITLE
眼镜连接手机,录制视频

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#106]
在眼镜连接手机后,怎么使用眼镜上的摄像头进行录制视频,
目前眼镜的api只返回了yuv数据,

**Comment by kaojin-alt** [comment]
如何能得到眼镜上摄像头的实例

**Comment by PuppiesMeat** [comment]
@kaojin-alt demo工程已经更新录制视频和拍照的示例 https://github.com/RokidGlass/RokidGlassMobileDemo
