### ISSUE TITLE
人脸识别动态更新人脸数据库未生效

### ISSUE THREAD

**Issue by up000** [RokidGlass/glass2-docs#110]
人脸识别，刚进入程序第一次初始化人脸数据库并添加数据是没有问题的，之后通过平台推送的数据加入人脸数据库，发现推送的人脸识别不了，但是测试该条数据已经成功加入人脸数据库了

**Comment by PuppiesMeat** [comment]
请提供以下信息：
1. 使用的sdk及sdk版本
2. 采用的方案是Dock+眼镜还是手机+眼镜
3. 添加数据的调用方式及添加数据后的操作
4. 测试数据已经成功加入人脸数据库是如何测试的

**Comment by up000** [comment]
1.sdk:facelib:4.16.3.3-cpu
2.Dock+眼镜
3.从接口获取人脸信息和图片base64数据列表，成功后创建FaceDbHelper对象，创建特征数据库，再将人脸信息加入UserInfoDao，之后直接进行人脸图片识别
4.添加人脸之后进入断点，打印人脸数据库数据列表，和添加的信息是一致的

今天，我试着创建人脸数据库后，先清空数据库，在添加人脸信息，发现人脸检测一开始就检测不出来了;如果不清空数据库，可以识别，但是动态添加的还是无法识别，怀疑检测读取的是上一次保存的人脸数据信息，而不是最新的人脸数据

**Comment by PuppiesMeat** [comment]
@up000 修改人脸数据库数据后需要重新初始化sdk

**Comment by up000** [comment]
解决了
