### ISSUE TITLE
Unity中，需要响应眼镜侧边的向前滑动和向后滑动事件，需要绑定哪些unity事件呀

### ISSUE THREAD

**Issue by warlock07** [RokidGlass/glass2-docs#112]
同标题

**Comment by XRWorld17** [comment]
Input.GetKeyDown(KeyCode.UpArrow        // KEYCODE_DPAD_UP
        
 Input.GetKeyDown((KeyCode.DownArrow  //KEYCODE_DPAD_DOWN
