### ISSUE TITLE
关于眼镜开发的技术支持问题！！！

### ISSUE THREAD

**Issue by Nicole-lailai** [RokidGlass/glass2-docs#117]
1  如果我没理解错，眼镜只是一个纯粹的显示器（附加摄像头麦克风和扬声器），并不带有任何计算设备和传感器。所有的计算单元，传感器和通讯模块全部都在那个小盒子。这个理解对吗？
  2  如果我上面的理解没问题，那么传感器的信息来源其实是小盒子而非眼镜，对吗？如果我需要判断当前用户头的指向方向（东西南北），使用传感器来做判断是会有问题的吗？我们需要使用安卓提供的Rotation Vector。
  3  我如何在电脑上开始开发流程？我把眼镜和小盒子用线连接好了，同时也把小盒子和电脑用线连接好了，小盒子也开机了。但是电脑上并没有看到这个设备。但是我没有找到任何说明如何打开adb 调试模式。所以Android Studio里也没法build进去。请问这个要怎么开启？
  4  我看你们的SDK里并没有提到如何在手机和眼镜之间传递信息。我只看到这个文档。但是其中应该分别在手机和眼镜的工程中如何设置并没有写的很清楚。希望能详细解释一下。
  5  我看你们手机和眼镜的连接是通过本地wifi网络进行互动。这个也是你们mobile SDK里默认的连接方式吗？你们在SDK里有没有提供蓝牙通讯的方式？我唯一看到你们文档里提到蓝牙是进行组网，但是没有提到可以进行通用的信息传输（API上看也并不支持）。
  6  如果你们SDK不提供蓝牙通讯方式，我们可不可以自己直接操作蓝牙模块？我们大概会用到这几个系统组件： android.bluetooth.BluetoothDevice, android.bluetooth.BluetoothGattCharacteristic, android.bluetooth.BluetoothGattServer, android.bluetooth.BluetoothGattService。

**Comment by shiwf** [comment]
> 1 如果我没理解错，眼镜只是一个纯粹的显示器（附加摄像头麦克风和扬声器），并不带有任何计算设备和传感器。所有的计算单元，传感器和通讯模块全部都在那个小盒子。这个理解对吗？
---摄像头、麦克风、传感器是位于眼镜上的，计算单元位于小盒子上。
> 2 如果我上面的理解没问题，那么传感器的信息来源其实是小盒子而非眼镜，对吗？如果我需要判断当前用户头的指向方向（东西南北），使用传感器来做判断是会有问题的吗？我们需要使用安卓提供的Rotation Vector。
---使用android标准的API获取的sensor数据，来源就是眼镜上，可以用来判断用户头指向的方向，可以直接获取到ROTATION_VECTOR
> 3 我如何在电脑上开始开发流程？我把眼镜和小盒子用线连接好了，同时也把小盒子和电脑用线连接好了，小盒子也开机了。但是电脑上并没有看到这个设备。但是我没有找到任何说明如何打开adb 调试模式。所以Android Studio里也没法build进去。请问这个要怎么开启？
---我们的系统是userdebug模式，默认adb调试是开启并直接授权的，理论上环境ok的话，adb是可以直接使用的，可以看下插口有没有插错。
> 4 我看你们的SDK里并没有提到如何在手机和眼镜之间传递信息。我只看到这个文档。但是其中应该分别在手机和眼镜的工程中如何设置并没有写的很清楚。希望能详细解释一下。
---眼镜+小盒子可以视作一个标准的android设备，你们可以选择wifi 蓝牙等方式自行开发与手机之间的数据通信
> 5 我看你们手机和眼镜的连接是通过本地wifi网络进行互动。这个也是你们mobile SDK里默认的连接方式吗？你们在SDK里有没有提供蓝牙通讯的方式？我唯一看到你们文档里提到蓝牙是进行组网，但是没有提到可以进行通用的信息传输（API上看也并不支持）。
---mobile SDK是指将眼镜直接插到手机上，不使用小盒子，而是使用手机作为计算单元，这种场景下使用的SDK。
> 6 如果你们SDK不提供蓝牙通讯方式，我们可不可以自己直接操作蓝牙模块？我们大概会用到这几个系统组件： android.bluetooth.BluetoothDevice, android.bluetooth.BluetoothGattCharacteristic, android.bluetooth.BluetoothGattServer, android.bluetooth.BluetoothGattService。
---可以自行开发蓝牙相关的数据通信。
