### ISSUE TITLE
眼镜系统无法连接macOS

### ISSUE THREAD

**Issue by pystone** [RokidGlass/glass2-docs#118]
最近刚刚收到Rokid Glasses2。收到之后可以开机和正常连接眼镜，但是无法连接到macOS上。`adb devices -l` 并没有显示出这个安卓设备。Android Studio中也并没有出现。与电脑连接的线在两个接口都尝试过，依然无法找到设备。请问是需要设置哪里才能打开调试模式吗？

**Comment by pystone** [comment]
USB-C的线也是没问题的 连接其他安卓手机都是正常 可以在 adb 中看到

**Comment by shiwf** [comment]
我们的眼镜默认开启usb 调试模式，
首先确认下线是否插错。Dock上有两个usb插口，其中较深的一个插眼镜，旁边画有一个眼镜和电池的标志；另一个带塞子的usb口子，是用来连接电脑调试用的，上面画有一个电脑的标志。
其次，请勿使用接眼镜的双头typc-c线连接Mac电脑，请使用type-A/C的线加转接头连接到Mac上。
如果上述两步都确认了，还是无法识别，请再确认下，是否开启了加密模式，开启后会自动禁用adb；如果没有开启加密模式，则到系统设置-本机信息界面，长按触摸板，会调起usb调试模式的开关，看下是否关闭了。

**Comment by pystone** [comment]
type-A/C加转接头就没问题了 多谢

**Comment by pystone** [comment]
还有一个问题 我把眼镜直接跟手机相连也是需要这样转接一下吗？我尝试了type-c/c 和 type-c/a + 转接头的方案 似乎都没什么效果。眼镜和手机相连之后会有什么效果吗？

**Comment by shiwf** [comment]
眼镜可以使用双头type-c直接跟手机相连，但是需要手机支持DP输出才可以正常使用，具体可以参考：
https://rokidglasses.gitee.io/glass2-docs/zh/7-glassmobile/res/mobile_glass/introduction.html

**Comment by pystone** [comment]
了解。多谢！
