### ISSUE TITLE
Glass2眼镜音频接口疑问

### ISSUE THREAD

**Issue by JamesLiao888** [RokidGlass/glass2-docs#120]
手机端如何获取眼镜MIC音频数据，手机端音频如何推送至眼镜喇叭发声？

在眼镜连接手机方案以下介绍文档中并未提及，请提供技术指导
https://rokidglasses.gitee.io/glass2-docs/zh/7-glassmobile/res/mobile_glass/introduction.html

**Comment by lanyuqingri** [comment]
手机连接眼镜时走的标准的UAC协议，眼镜的mic和speaker 会作为标准的外设被android系统挂载上去，android系统一般默认会把mic & speaker指向此外接的设备上，直接使用AudioRecord & MediaPlayer原生方法即可使用。
