### ISSUE TITLE
下载的demo运行不起来的问题

### ISSUE THREAD

**Issue by yehzou** [RokidGlass/glass2-docs#121]
下载的demo运行不起来，报这个错，Unable to load class 'javax.xml.bind.JAXBException'.    我也换成了jdk8,直接其它项目可以跑；也加入 了javax.activation-1.2.0.ja ，jaxb-api-2.3.0.jar，jaxb-core-2.3.0.jar，jaxb-impl-2.3.0.jar这四个到lib,还是报Unable to load class 'javax.xml.bind.JAXBException

**Comment by lanyuqingri** [comment]
你好，请问下载的是哪个SDK的Demo，主要使用在什么场景下？

**Comment by lanyuqingri** [comment]
最佳实践的Demo 是指手机接眼镜方案的Demo吗？  看报错貌似是系统JDK相关的环境变量的问题

**Comment by lanyuqingri** [comment]
能否将你那边环境配置的截图上传一下，jdk 以及sdk相关的，另外把全部的报错信息贴一下？我们这边目前没出现过类似的报错，网上查资料也是指向环境配置这块

**Comment by yehzou** [comment]
![图片](https://user-images.githubusercontent.com/28803313/117950095-6a272e00-b345-11eb-9e84-292754ba2fab.png)
![图片](https://user-images.githubusercontent.com/28803313/117950254-93e05500-b345-11eb-8e9a-05766086cf97.png)
![图片](https://user-images.githubusercontent.com/28803313/117952538-d4d96900-b347-11eb-8442-7e65e0451d49.png)
![图片](https://user-images.githubusercontent.com/28803313/117952629-eb7fc000-b347-11eb-94fd-425d0416b298.png)
![图片](https://user-images.githubusercontent.com/28803313/117952712-ffc3bd00-b347-11eb-8fe4-4daf57d576fa.png)
是AllianceDemo这个人脸车牌识别——手机接眼镜模式的项目

**Comment by lanyuqingri** [comment]
![image](https://user-images.githubusercontent.com/10458182/117953444-9b552d80-b348-11eb-9be7-11a742f9d88f.png)
androidstudio中配置的JDK 以及sdk相关的配置能否也贴一下？

**Comment by yehzou** [comment]
![图片](https://user-images.githubusercontent.com/28803313/118059836-009a3480-b3c4-11eb-9b10-e085ed241626.png)

**Comment by yehzou** [comment]
![图片](https://user-images.githubusercontent.com/28803313/118061229-2117be00-b3c7-11eb-8a18-2fb4a72c8c85.png)

**Comment by yehzou** [comment]
可以了，调整好了，现在跑起来了，还是jdk配置问题，多谢了

**Comment by lanyuqingri** [comment]
环境问题，已解决，issue closed
