### ISSUE TITLE
摄像头对焦问题

### ISSUE THREAD

**Issue by yoona1992** [RokidGlass/glass2-docs#125]
摄像头无法对焦，有没有相关的摄像头自动对焦代码可以提供下

**Comment by lanyuqingri** [comment]
请问使用的是那款眼镜？ 具体的使用方式是怎样的？

**Comment by yoona1992** [comment]
Rokid Glass2，使用方式是用你们的demo跑的项目，然后发现无法自动对焦

**Comment by lanyuqingri** [comment]
具体是那套SDK对应的Demo工程呢？

**Comment by yoona1992** [comment]
RokidFaceSDK，这一套。比如我手里拿张身份证，放在眼镜前面，我在眼镜里面看到的身份证上面的字就是模糊的

**Comment by lanyuqingri** [comment]
在这套Demo中Camera 是使用的一个三方库，目前自动对焦功能眼镜是支持的，使用标准的Camera的API就可以开启，目前我们这边使用的Camera2 的API，示例如下
mPreviewRequestBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);

**Comment by yoona1992** [comment]
再问个连接手机的问题，为什么用mate30，用usb方式连接连接眼镜，眼镜画面不连贯，运行十几秒之后手机上显示的眼镜画面就不动了。过一会就提示是否允许访问该USB设备

**Comment by lanyuqingri** [comment]
应该是连接线的问题，建议沟通一根绿联的比较粗的连接线，连接更稳定一些，具体购买链接： https://item.m.jd.com/product/41159484004.html?wxa_abtest=o&gx=RnEyyzNZPD3dn9QXqoN-WMJA4Dc2yhY&ad_od=share&utm_source=androidapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=Wxfriends
