### ISSUE TITLE
离线人脸识别 获取到bitmap为空

### ISSUE THREAD

**Issue by sadais-fuwenlong** [RokidGlass/glass2-docs#126]
videoFace.startTrack(model -> {
            Log.i(TAG,"model:"+model.toString());
            //用于显示返回的人脸model
            faceModelView.setFaceModel(model);
            if(ObjectUtils.isEmpty(model)||ObjectUtils.isEmpty(model.getMaxFace()))return;
            getPersonByBitmap(model.getMaxFace().recogBitmap);
        });

获取到recogBitmap为空

**Comment by PuppiesMeat** [comment]
@sadais-fuwenlong 麻烦先提供使用的Rokid 所有SDK及SDK版本， 离线人脸识别如果没有没有识别到在数据库的人员不会有bitmap返回

**Comment by sadais-fuwenlong** [comment]
是不在数据库中的人脸，我们的使用场景，只需要识别到人脸即可，核对身份是要将抓到的人脸图片给后台去检测

**Comment by sadais-fuwenlong** [comment]
那要如何获取识别到的人脸图片呢

**Comment by PuppiesMeat** [comment]
这里有一段伪代码 可以参考下
   videoFace.startTrack(new RokidFaceCallback() {
            @Override
            public void onFaceCallback(final FaceModel model) {
                // 检测到有人脸数据则展示人脸数据
                boolean isMultiFaceRecg = BaseLibrary.getInstance().isMultiFaceRecgEnable();
                boolean isSingleFaceRecg = BaseLibrary.getInstance().isSingleFaceRecgEnable();
                boolean ignoreCopyData = false;
                if (null == model || null == model.getFaceList() || model.getFaceList().size() == 0) {
                    //未检测到人脸
                    return;
                }
                //之后可能异步处理，所以这里copy一份数据
                FaceModel faceModel = FaceUtil.copyFaceModel(model);
                //originData是Camera出来的数据 格式是nv21
                byte[] originData = videoFace.getBytes();
                byte[] data = ByteArrayPool.defaultPool().getBuf(originData.length);
                System.arraycopy(originData, 0, data, 0, originData.length);
                Logger.d("onFaceCallback------>isMultiFaceRecg = " + isMultiFaceRecg + " && isSingleFaceRecg = " + isSingleFaceRecg);
                FaceDO targetFace = model.getMaxFace();
                if (targetFace == null ){
                    return;
                }

                if(targetFace.quality >= 45) {//质量合格
                    Logger.i("-----goodQuality-------");
                    Rect faceRect = targetFace.toRect(CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT);
                    Rect finalRect = FaceRectUtils.scaleRect(faceRect,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,1.6f);
                    Bitmap bm = BitmapUtils.nv21ToBitmap(data,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,finalRect);
                    mRecgCaptureBitmap = BitmapUtils.nv21ToBitmap(data,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT);
                    doNetWork(value,bm);
                }else{//质量不合格
                    if(targetFace.quality > mCurrentQuality && targetFace.quality >= 42){ //超过42分 并且超过了当前此人的最高质量，暂存 直到超时再上传
                        Rect faceRect = targetFace.toRect(CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT);
                        Rect finalRect = FaceRectUtils.scaleRect(faceRect,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,1.6f);
                        mBestBitmap = BitmapUtils.nv21ToBitmap(data,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,finalRect);
                        mCurrentQuality = targetFace.quality;
                    }
                    if(targetFace.trackInterval > 1000) { //此人已经超过1秒钟暂存了，选取最高质量的一张抠图上传，如果没有一张超过42分 则不会上传（mBestBitmap为空）
                        Logger.i("-----timeOut-------");
                        mCurFaceFirstTime = -1;
                        if(mBestBitmap != null){
                            mRecgCaptureBitmap = BitmapUtils.nv21ToBitmap(data,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT);
                            doNetWork(value,mBestBitmap);
                        }
                    }
                }
            }
        });

**Comment by sadais-fuwenlong** [comment]
好的，我试一下，谢谢
