### ISSUE TITLE
字体大小不固定

### ISSUE THREAD

**Issue by 0xRookie** [RokidGlass/glass2-docs#127]
如下代码给图片添加水印,textsize设置为固定大小，但是绘制到bitmap上会呈现出近大远小的现象。我想问下，如何才能绘制出固定字体大小的文字？
`mPaint = new TextPaint(Paint.ANTI_ALIAS_FLAG);
        mPaint.setStrokeWidth(4);
        mPaint.setStyle(Paint.Style.STROKE);
        mPaint.setColor(Color.WHITE);
        mPaint.setTextSize(40);`
` public static Bitmap textWaterMark(Bitmap bitmap, CharSequence text, TextPaint paint) {
        Bitmap newBitmap = Bitmap.createBitmap(bitmap.getWidth(), bitmap.getHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(newBitmap);
        canvas.drawBitmap(bitmap, 0, 0, paint);
        StaticLayout staticLayout = new StaticLayout(text, paint, bitmap.getWidth(), Layout.Alignment.ALIGN_OPPOSITE, 0, 0, false);
        staticLayout.draw(canvas);
        return newBitmap;
    }
`

**Comment by sunchaonew** [comment]
请问您说的近大远小，是字体大小随控件大小改变吗

**Comment by sunchaonew** [comment]
看上面的方案是在bitmap上添加文字，需要使控件适配bitmap的大小，设置的字体大小才能生效。没有其他问题这个issue就先关闭了
