### ISSUE TITLE
Question regarding Rokid InstructLifeManager

### ISSUE THREAD

**Issue by eaaliprantis** [RokidGlass/glass2-docs#132]
Hi.

Currently using Android Studio (not Unity):

So i currently have multiple activites.  I am using the InstructLifeManager to initialize on each activity.  Initial activity registers voice commands.  However, navigating to next activity, i lose voice.  Therefore i am unable to use voice commands.

When navigating to a new activity, how to properly clear / delete old instructlifemanager listener to use the new one on the next activity? OR:

What is the proper steps to handle different activity navigation / transition that uses InstructLifeManager?

**Comment by eaaliprantis** [comment]
Note: not using InstructActivity

**Comment by WanderingGavin** [comment]
Each activity needs to initialize its own instruction group. The instruction group is set in the onResume() of the Activity, and onPause() cycle stops responding. Instructlifemanager should initialize an instance in each activity. If you need to modify the instruction phrase after Activity onResume(), you can use

mLifeManager.getInstructConfig().addInstructEntity(new InstructEntity()...);
mLifeManager.sendWtWords();

To reset the instruction group on this Activity

Some other ways of use the instruct sdk , can be referred to 
https://github.com/RokidGlass/Rokid_APG_VoiceInstructDemo

**Comment by eaaliprantis** [comment]
HI @WanderingGavin 

For clarification, you are stating that for each activity, the instruction group commands need to be different than the previous activity?

What if there are commands that are needed for both activity? would that then be a global instruct command?

**Comment by WanderingGavin** [comment]
Hi，@eaaliprantis
1. Global voice instructions can be added in your app Application through VoiceInstruction. The global will take effect in all the Activities that use InstructLifeManager in the current process.
eg：
public class InstructApplication extends Application {

    /**
     * 设置ManagerBasicSkill的context
     */
    @Override
    public void onCreate() {
        super.onCreate();

        VoiceInstruction.init(this);
        VoiceInstruction.getInstance().addGlobalInstruct(
                new InstructEntity()
                        .setGlobal(true)
                        .addEntityKey(new EntityKey("返回", "fan hui"))
                        .addEntityKey(new EntityKey(EntityKey.Language.en, "back last page"))
                        .setCallback(new IInstructReceiver() {
                            @Override
                            public void onInstructReceive(Activity act, String key, InstructEntity instruct) {
                                try {
                                    if (act != null) {
                                        act.finish();
                                    }
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }
                        })
        );
    }
}

2. InstructLifeManager can be used as a simple tool. The constructor of InstructLifeManager requires the user to provide LifeCycle. The current demo is provided by AppCompatActivity. You can create your own LifecycleOwner in Application.
To Implementing a custom LifecycleOwner, please refer to:
https://developer.android.com/topic/libraries/architecture/lifecycle#implementing-lco

 mLifeManager = new InstructLifeManager(this, yourLifecycle(), mInstructLifeListener);

The voice command group will be set to the system in the ON_RESUME of LifeCycle, and removed from the system in the ON_PAUSE. It can be used after modifying the instruction at the same time:

mLifeManager.getInstructConfig().addInstructEntity(new InstructEntity()...);
mLifeManager.sendWtWords();

To update the content of the voice command group.

**Comment by eaaliprantis** [comment]
Hi @WanderingGavin 

This actually helped and i have made more progress (and able to use it in each activity).

However, is it possible to use voice in an android service instead of an activity? or is that not possible?

**Comment by WanderingGavin** [comment]
Hi，@eaaliprantis
    Same as I said before，InstructLifeManager can be used as a simple tool，no matter where it is used. Member parameters “LifeCycle” just use to trigger automatic setting instructions，You can customize one yourself LifecycleOwner in Application，used to provide LifeCycle to InstructLifeManager。such as your want，use InstructLifeManager in an Android service ：
    
    1. Create own LifecycleOwner in Application or your service，Can refer to https://developer.android.com/topic/libraries/architecture/lifecycle#implementing-lco

    private LifecycleRegistry lifecycleRegistry;

    @Override
    public void onCreate() {
        super.onCreate();

        lifecycleRegistry = new LifecycleRegistry(this);
        lifecycleRegistry.markState(Lifecycle.State.CREATED);
    }

    @NonNull
    @Override
    public Lifecycle getLifecycle() {
        return lifecycleRegistry;
    }

    2. new a InstructLifeManager in Application or your service：
        mLifeManager = new InstructLifeManager(this, getLifecycle(), mInstructLifeListener);

    3. make own LifecycleOwner  to Lifecycle.State.RESUMED：
        lifecycleRegistry.markState(Lifecycle.State.RESUMED);

    4. set or change your instruct group，then send to rokid voice assistant：
        mLifeManager.getInstructConfig().addInstructEntity(new InstructEntity()...);
        or
        mLifeManager.getInstructConfig().addInstructList(** need a List<InstructEntity> instructList **);

        mLifeManager.sendWtWords();

    5. when you want change your instruct group，just repeat the fourth step：
        mLifeManager.getInstructConfig().clearUserInstruct();
        mLifeManager.getInstructConfig().addInstructList(** need a List<InstructEntity> instructList **);
        mLifeManager.sendWtWords();

Hope it helps you ！

**Comment by eaaliprantis** [comment]
Hi @WanderingGavin,

Would you be able to provide a sample of the voice in a service class (like Accessibility Service class)? I've been having some difficulty with getting it to work in a Service.

**Comment by WanderingGavin** [comment]
Hi, @eaaliprantis
      Currently, our SDK does not support Accessibility Service。And, we want to use voice commands through Activity UI 。In the previous sdk, InstructLifeManager will have some problems without using Activity initialization. You can upgrade your sdk version to 1.6.1.

implementation 'com.rokid.ai.glass:instructsdk:1.6.1'

then the Service：

public class InstructTestService extends Service implements LifecycleOwner {

    private static final String TAG = "AudioAi " + InstructTestService.class.getSimpleName();

    private LifecycleRegistry mLifecycleRegistry;
    private InstructLifeManager mLifeManager;
    private List<InstructEntity> mInstructEntityList;

    @Override
    public void onCreate() {
        super.onCreate();
        mLifecycleRegistry = new LifecycleRegistry(this);
        mInstructEntityList = new ArrayList<>();
        mLifecycleRegistry.markState(Lifecycle.State.CREATED);
        mLifeManager = new InstructLifeManager(this, getLifecycle(), mInstructLifeListener);
        mLifecycleRegistry.markState(Lifecycle.State.RESUMED);
        Log.d(TAG, "InstructTestService onCreate()");
    }

    private InstructLifeManager.IInstructLifeListener mInstructLifeListener = new InstructLifeManager.IInstructLifeListener() {
        @Override
        public boolean onInterceptCommand(String command) {
            return false;
        }

        @Override
        public void onTipsUiReady() {
            // no UI, can not be call back
        }

        @Override
        public void onHelpLayerShow(boolean show) {
            // no UI, can not be call back
        }
    };

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        Log.d(TAG, "InstructTestService onBind()");
        return testService.asBinder();
    }

    private ITestService testService = new ITestService.Stub() {

        @Override
        public void addInstruct(String type, String item) throws RemoteException {
            Log.d(TAG, "ITestService addInstruct item = " + item);
            if (TextUtils.isEmpty(type) || TextUtils.isEmpty(item)) {
                return;
            }
            InstructEntity entity = new InstructEntity();
            entity.addEntityKey(new EntityKey(
                    (EntityKey.Language.zh.name().equals(type.toLowerCase()) ? EntityKey.Language.zh
                            : EntityKey.Language.en), item));
            entity.setCallback(new IInstructReceiver() {
                @Override
                public void onInstructReceive(Activity act, String key, InstructEntity instruct) {
                    //  act is null
                    Log.d(TAG, "tool instruct call back: --> " + key);
                }
            });
            if (mInstructEntityList != null) {
                mInstructEntityList.add(entity);
            }
        }

        @Override
        public void sendInstruct() throws RemoteException {
            Log.d(TAG, "ITestService sendInstruct ");
            if (mLifeManager != null) {
                mLifeManager.clearUserInstruct();
                mLifeManager.addInstructList(mInstructEntityList);
                mLifeManager.sendWtWords();
            }
        }
    };

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        Log.d(TAG, "InstructTestService onStartCommand()");
        return super.onStartCommand(intent, flags, startId);
    }

    @NonNull
    @Override
    public Lifecycle getLifecycle() {
        return mLifecycleRegistry;
    }

    @Override
    public void onDestroy() {
        Log.d(TAG, "InstructTestService onDestroy()");
        if (mLifecycleRegistry != null) {
            mLifecycleRegistry.markState(Lifecycle.State.DESTROYED);
        }

        if (mLifeManager != null) {
            mLifeManager.onDestroy();
            mLifeManager = null;
        }
        super.onDestroy();
    }
}

For details, you can refer to
https://github.com/RokidGlass/Rokid_APG_VoiceInstructDemo
update it in master branch，and see InstructTestService、ServiceTestAct

**Comment by eaaliprantis** [comment]
Hi @WanderingGavin 

I test this and this was unable to work in the AccessibiltyService that I have created.  Is it possible to create intents / broadcast receiver to tie into the Rokid system?

For instance, 1. an intent to request to add words to the on-board voice (instead of the app voice)
2. an intent to request to retrieve word that was said if it matches
These intents would help with retrieving and adding words to either the global list or not and therefore be able to work when the app is closed :)

**Comment by WanderingGavin** [comment]
Hi, @eaaliprantis
      Rokid instructSdk unable to work in the AccessibiltyService, it can be use in normal Service in a app.  
      I don't think instructSdk suits your idea。

**Comment by eaaliprantis** [comment]
Hi @WanderingGavin 

Wouldthere be a way to inject / communicate with the on-board voice (like using intents) to communicate with adding voice to it?

**Comment by WanderingGavin** [comment]
Hi, @eaaliprantis
     At present, we only support active voice setting through instructsdk, has no way to inject / communicate with the on-board voice. If you want to get more functions, you can read the source code of instructsdk through Android studio, and then directly simulate the implementation of instructlifemanager in instructsdk. Instructsdk source code is very few, not complex.

**Comment by eaaliprantis** [comment]
Hi @WanderingGavin 

Thank you.  That makes sense.

I was wondering if you would be able to provide an example with properly scaling a webview.  

Currently, when opening up a webpage in a webview, it pulls up a 640x360 resolution instead of the 1280x720 resolution.

**Comment by WanderingGavin** [comment]
Hi, @eaaliprantis
Sorry, we don't use webview in our app. We need to study your situation about webview. For the third-party app, if it is not horizontal screen, we will use the vertical screen mode of simulated mobile phone. Black edges on both sides and a vertical screen app in the middle.

**Comment by eaaliprantis** [comment]
Hi @WanderingGavin 

That makes sense.

On a browser, we have the camera working on the device (web rtc type like) but on the other end, they are unable to view the camera that is shown on the app.  What is the proper way to access the camera through the web rtc so that both parties are able to receive both video and audio ends (note: audio works; video viewing is not)

**Comment by WanderingGavin** [comment]
Hi @eaaliprantis 
     
Thank you for providing usage information for this scene.

Our cameras are direct-configured USB cameras as the main cameras of the system, following Android's cameras related Hal layer driver protocol.However, I'm sorry, we haven't tried to develop conference applications using webrtc yet. Our remote collaboration app uses a third-party company's conference system sdk, currently not have this problem.

We'll look at this issue later about direct use of webrtc.

**Comment by eaaliprantis** [comment]
Hi @WanderingGavin 

Thank you for the help :)
