### ISSUE TITLE
调用视频播放器播放本地文件

### ISSUE THREAD

**Issue by OneCats** [RokidGlass/glass2-docs#147]
如何调用视频播放器播放本地生成文件?

**Comment by sunchaonew** [comment]
你好 
可以参考一下：
https://rokidglass.github.io/glass2-docs/zh/1-system/sysapp.html
最下面”我的文件“的部分

**Comment by OneCats** [comment]
我试了一下,他跳转过去后,界面只有一个"+"号,界面都是黑色的,也没有提示"找不到文件".文件是存在的,因为我这边的缩略图和上传都已经成功了

**Comment by sunchaonew** [comment]
你的文件直接放到我的文件中（Documents文件夹下）是可以显示的吗？还有问题的话调用方式发一下吧

**Comment by OneCats** [comment]
因为我这边看不到系统文件路径,您发我一份具体的存储路径

**Comment by OneCats** [comment]
![image](https://user-images.githubusercontent.com/45055504/122879538-9766f300-d36b-11eb-8f47-147100d9c22b.png)

**Comment by OneCats** [comment]
改到（Documents文件夹下）我的文件是可以显示的，但是直接打开文件还是不行。

**Comment by sunchaonew** [comment]
intent.putExtra("file_name", fileName);//文件名称，带后缀名
这个参数有传吗？后缀有加吗

**Comment by OneCats** [comment]
嗯嗯，可以了。需要将文件名和文件路径一块传递，就可以打开了。谢谢
