### ISSUE TITLE
使用UXR SDK和Sample打包后的App，运行后双目画面分离

### ISSUE THREAD

**Issue by duanyunlun** [RokidGlass/glass2-docs#159]
完全按照官方指引打包，没修改任何代码和文件，运行后双目画面分类，且Android Logcat显示以下报错信息
![image](https://user-images.githubusercontent.com/15923235/127124669-a43e33fa-0a95-434c-a180-10550a8619aa.png)

**Comment by XRWorld17** [comment]
> 完全按照官方指引打包，没修改任何代码和文件，运行后双目画面分类，且Android Logcat显示以下报错信息
> ![image](https://user-images.githubusercontent.com/15923235/127124669-a43e33fa-0a95-434c-a180-10550a8619aa.png)

请问系统软件的版本号，以及UXR SDK版本号是多少

**Comment by duanyunlun** [comment]
> > 完全按照官方指引打包，没修改任何代码和文件，运行后双目画面分类，且Android Logcat显示以下报错信息
> > ![image](https://user-images.githubusercontent.com/15923235/127124669-a43e33fa-0a95-434c-a180-10550a8619aa.png)
> 
> 请问系统软件的版本号，以及UXR SDK版本号是多少

Windows版本信息：
![image](https://user-images.githubusercontent.com/15923235/127248687-aae5567f-d7fe-4107-907a-5c0744cc3390.png)
Unity版本：2020.1.17f1c1
UXR版本：RokidUXR_Unity_ForDock_1.5.3

**Comment by XRWorld17** [comment]
头环的系统版本是多少？
SDK Sample中有一个编译好的apk,在头环上运行是否正常？

**Comment by duanyunlun** [comment]
头环版本为：1.3.5-20210611-502103（试过点击升级，提示为最新版）
SDK Sample内的编译好的apk放进去依然是双目分离画面

**Comment by XRWorld17** [comment]
> 头环版本为：1.3.5-20210611-502103（试过点击升级，提示为最新版）
> SDK Sample内的编译好的apk放进去依然是双目分离画面

RG-crown系统版本要求最低1.3.5-20210618-502103，可通过相关升级指导进行升级

**Comment by duanyunlun** [comment]
有没有相关升级指导的链接？
