### ISSUE TITLE
Fail to install "arm64-v8a" APK  to Rokid Glass 2

### ISSUE THREAD

**Issue by Dav151** [RokidGlass/glass2-docs#163]
Hi,

After compile to target "arm64-v8a" APK successfully, it fails to install the APK into the glass device using Android Studio.
The Android Studio shows "Droidlogic cyclops (Device supports armeabi-v7a, armeabi, but APK only supports arm64-v8a"

Thanks

**Comment by Machaojoy** [comment]
> Hi,
> 
> After compile to target "arm64-v8a" APK successfully, it fails to install the APK into the glass device using Android Studio.
> The Android Studio shows "Droidlogic cyclops (Device supports armeabi-v7a, armeabi, but APK only supports arm64-v8a"
> 
> Thanks

Hello,dav151,
Device supports armeabi-v7a, armeabi.

**Comment by Dav151** [comment]
Hi Machaojoy,

Yes, i can install armeabi-v7a APK, and want to use 64bit for better performance.

Rokid Glass 2 use Amlogic 905D3 as CPU which is "Quad core ARM Cortex-A55", and it supports "ARMv8-A architecture" in the specification.

Note sure it is correct or not.

Thanks

**Comment by Machaojoy** [comment]
> Hi Machaojoy,
> 
> Yes, i can install armeabi-v7a APK, and want to use 64bit for better performance.
> 
> Rokid Glass 2 use Amlogic 905D3 as CPU which is "Quad core ARM Cortex-A55", and it supports "ARMv8-A architecture" in the specification.
> 
> Note sure it is correct or not.
> 
> Thanks

Soc Chip support ARMv8，But Amlogic  solution only support ARMv7

**Comment by Machaojoy** [comment]
Thanks,Welcome to contact us anytime
