### ISSUE TITLE
rokid issue

### ISSUE THREAD

**Issue by Kittametgolf** [RokidGlass/glass2-docs#172]
i have some problem when update software. it look like has some bug or something  on background when use hardware.

**Comment by shiwf** [comment]
Could you please describe the issue in detail?

**Comment by Kittametgolf** [comment]
after i install unity apk in  ROKID X-CRAFT . and use application for 10 minute . monitor it look like has problem.it has only me can see it .if record it. ill be normal but  if see on hardware it look not good

**Comment by shiwf** [comment]
1. Please tell us your OS version and device SN。
2. What Unity apk？Do you use our UXR SDK? Can you send the apk to us?

**Comment by Kittametgolf** [comment]
1. system ver. 2.0.2-20210716-502102
2. Dock SN 0922022121000158

**Comment by Kittametgolf** [comment]
I CANNOT SEND APK . can i send it from another way ?

**Comment by Kittametgolf** [comment]
[https://we.tl/t-pXsZwk9qLB](url)

**Comment by shiwf** [comment]
> I CANNOT SEND APK . can i send it from another way ?

Can you upload the apk to somewhere such as cloud storage and then we can download it?

**Comment by Kittametgolf** [comment]
I already upload to wetransfer Can u download it ?

**Comment by Machaojoy** [comment]
Can you take a picture of the display with your phone?
