### ISSUE TITLE
Rokid X-Graft使用UXR SDK开发

### ISSUE THREAD

**Issue by zhang582187919** [RokidGlass/glass2-docs#178]
UXR  SDK 中的API只介绍了语音指令的添加删除，手势识别的开关，屏幕渲染这些，有没有比较详细的内容，比如语音指令检测执行后的回调调用方法，手势识别后的反馈在哪里接收

**Comment by XRWorld17** [comment]
1. 语音回调参考API示例，详见Sample工程中C#脚本，例如
   AddInstrucEntityZH("下一个", pinyin, "VoiceRecognizer","unitydoNext","xyg")

2. 手势反馈参考Sample工程中
    RKGesSampleInteraction.cs

**Comment by zhang582187919** [comment]
工程在哪里下载




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RokidGlass/glass2-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RokidGlass/glass2-docs] Rokid X-Graft使用UXR SDK开发 (#178)





  
 
语音回调参考API示例，详见Sample工程中C#脚本，例如
 AddInstrucEntityZH("下一个", pinyin, "VoiceRecognizer","unitydoNext","xyg")
 
 
 
手势反馈参考Sample工程中
 RKGesSampleInteraction.cs
 
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XRWorld17** [comment]
> 工程在哪里下载
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "RokidGlass/glass2-docs" ***@***.***&gt;; 发送时间:&nbsp;2021年8月24日(星期二) 中午11:49 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [RokidGlass/glass2-docs] Rokid X-Graft使用UXR SDK开发 (#178) 语音回调参考API示例，详见Sample工程中C#脚本，例如 AddInstrucEntityZH("下一个", pinyin, "VoiceRecognizer","unitydoNext","xyg") 手势反馈参考Sample工程中 RKGesSampleInteraction.cs — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

请问在哪里看到的API文档，UXR文档中有下载地址的

**Comment by zhang582187919** [comment]
在官网上看到的，但是里边没有下载链接




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RokidGlass/glass2-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 下午2:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RokidGlass/glass2-docs] Rokid X-Graft使用UXR SDK开发 (#178)





  
工程在哪里下载
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "RokidGlass/glass2-docs" @.&gt;; 发送时间:&nbsp;2021年8月24日(星期二) 中午11:49 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [RokidGlass/glass2-docs] Rokid X-Graft使用UXR SDK开发 (#178) 语音回调参考API示例，详见Sample工程中C#脚本，例如 AddInstrucEntityZH("下一个", pinyin, "VoiceRecognizer","unitydoNext","xyg") 手势反馈参考Sample工程中 RKGesSampleInteraction.cs — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
请问在哪里看到的API文档，UXR文档中有下载地址的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XRWorld17** [comment]
> 在官网上看到的，但是里边没有下载链接
> […](#)

上述官网的地址是？

**Comment by yuyunjing** [comment]
Rokid 开放文档地址请使用：https://rokid.yuque.com/books/share/7b325232-3dae-4ed2-8821-93f915d1ef95?# 《开发者文档（中文）》
