### ISSUE TITLE
UXR SDK是不对外开放吗，找不到下载的地方

### ISSUE THREAD

**Issue by zhang582187919** [RokidGlass/glass2-docs#179]

**Comment by yuyunjing** [comment]
以下链接是开发者文档：https://rokid.yuque.com/books/share/7b325232-3dae-4ed2-8821-93f915d1ef95?# 《开发者文档（中文）》
请根据自己的设备，选择对应目录，UXR SDK 目前只在两种设备中支持，Rokid Air+Rokid X-Craft。
![image](https://user-images.githubusercontent.com/81565266/131816295-adf31f72-5d0e-49ed-a657-ef8fd54aa3f8.png)
