### ISSUE TITLE
设置静态IP

### ISSUE THREAD

**Issue by BruceeSU** [RokidGlass/glass2-docs#186]
现在做的一个项目需要连接到一个WiFi后设置静态IP，眼镜端没有设置界面，请问这个要怎么设置？

**Comment by BruceeSU** [comment]
我尝试通过调用安卓原生API来设置静态IP，但是没法设置成功，咨询了下做安卓开发的朋友，说这是系统级别设置，需要厂家提供一个APK签名才能有权限，是这样吗？如果不是，请问官方有没有一个相关的代码作为参考，这块确实不太熟悉

**Comment by shiwf** [comment]
可以使用PC助手工具，投屏拉起系统原生设置，在系统原生设置中配置wifi。
https://ar.rokid.com/detail?appId=b6f800a4d8764e3088ab2f138d263492&lang=cn

**Comment by yuyunjing** [comment]
应用内置使用说明书，获取路径：
![image](https://user-images.githubusercontent.com/81565266/133588094-7c4ac669-ed57-4c99-a27d-ed96253779bd.png)
![image](https://user-images.githubusercontent.com/81565266/133588144-907bb2ca-6ade-4804-ae8c-c71364d11af6.png)

**Comment by BruceeSU** [comment]
PC助手里的WiFi配置界面并没有设置静态IP的选项，只能看到一些信息但是无法修改

**Comment by shiwf** [comment]
原生设置里，添加网络，展开高级选项，高级选项里有设置静态ip

**Comment by BruceeSU** [comment]
好的，找到了，十分感谢
