### ISSUE TITLE
GlassUI的Demo

### ISSUE THREAD

**Issue by NCEPU-211** [RokidGlass/glass2-docs#187]
官网提供的GLassUI的demo下载之后，具体如何使用AndroidStudio运行呢。自己在导入之后，一直有各种问题。

**Comment by yuyunjing** [comment]
那么具体出现了什么问题呢？然后再告知下硬件是什么

**Comment by NCEPU-211** [comment]
AndroidStudio报错信息部分：
Gradle sync failed: Could not resolve all dependencies for configuration ':demo:debugRuntimeClasspath'.
			Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven(http://mvnrepo.rokid-inc.com/nexus/content/groups/public/)' to redirect to a secure protocol (like HTTPS) or allow i



硬件是Rokid Glass，目前就是从官网下载了demo，然后导入了AndroidStudio，然后sync gradle这一步就一直过不去

**Comment by sunchaonew** [comment]
你好，可以先将上面的maven库，替换为maven {url('https://maven.rokid.com/repository/maven-public/')}
demo可能是之前的没有更新，后续会更新下

**Comment by NCEPU-211** [comment]
感谢您的解答，问题还是报错，报错原因没有变，有没有可能是build tools的错误呢，或者是其他设置上面的

**Comment by sunchaonew** [comment]
只保留上面一个maven库，将原来的maven库相关的代码：
        classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6"
        classpath "com.github.dcendents:android-maven-gradle-plugin:1.5"
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.5.4"
这些都注掉试试吧

**Comment by NCEPU-211** [comment]
好的，特别感谢你，我明天试一下哈

**Comment by NCEPU-211** [comment]
图片1[http://m.qpic.cn/psc?/V5429JaG3FReLM30iTBn0qYiJF1YzyOO/45NBuzDIW489QBoVep5mcUvo9uJ2q6QJQyEQtt593pZeaTflsCZLcOPc0Hxv*3H3zPLrdCwljki*2Y7Wu1nKIYs4AV*8jC7qRPmEDuPSuHg!/b&bo=gAcPBAAAAAADJ44!&rf=viewer_4](url)
图片2[http://m.qpic.cn/psc?/V5429JaG3FReLM30iTBn0qYiJF1YzyOO/45NBuzDIW489QBoVep5mcUvo9uJ2q6QJQyEQtt593pYyvn*DblEcF.8fyCXErVUhSBJUiHZRs0KdS700k4uW.FNQGolfBO6PNUbZhmBh954!/b&bo=gAcPBAAAAAADJ44!&rf=viewer_4](url)
图片3[http://m.qpic.cn/psc?/V5429JaG3FReLM30iTBn0qYiJF1YzyOO/45NBuzDIW489QBoVep5mcUvo9uJ2q6QJQyEQtt593pbbV9eZWhbF74YpjC5VeGScRrZ3f.vwWixf3rzYXtYHso18iMUpicDjuijSlscyj*M!/b&bo=gAcPBAAAAAADN54!&rf=viewer_4](url)
图片4[http://m.qpic.cn/psc?/V5429JaG3FReLM30iTBn0qYiJF1YzyOO/45NBuzDIW489QBoVep5mcUvo9uJ2q6QJQyEQtt593pZOfL*nc13TuPgPikcJ0MKQIOgC0viS9ICrdG8ZnbAI70v7qLch4LXYT*Vr1pQ1mH0!/b&bo=gAcPBAAAAAADJ44!&rf=viewer_4](url)

你好，上面是四个图片的链接，前两个是配置的图片，后面两个是运行后的信息，之前的报错没有了，但是这个配置过程花了一个小时，而且也没有配置成功，麻烦您看一下是什么问题呢，这个Android Studio问题总是特别多，自己看着csdn上的解决办法很少能成功解决

**Comment by sunchaonew** [comment]
你好，看你提供的报错图片是在下载android 的constraint库，是不是网络问题没有下载下来，可以换成使用流量下载试试。
还有问题可以试下把glassui的引用去掉。
也可以参考https://rokid.yuque.com/docs/share/6fd1916d-f726-4b03-8d45-c85565dbea36?# 《UI SDK》
的集成部分，在自己项目里集成

**Comment by NCEPU-211** [comment]
好的好的 谢谢您

**Comment by luvsuck** [comment]
@sunchaonew 您好，我确认下，现在是这个域名 mvnrepo.rokid-inc.com 弃用了，全部替换成maven.rokid.com么

**Comment by sunchaonew** [comment]
你好  是的

**Comment by luvsuck** [comment]
@sunchaonew 您好，最好找个时间更新下demo吧 ，麻烦您了。。

**Comment by sunchaonew** [comment]
好的，更新应该就是按最上面说的替换一下maven地址，可能需要两三天后

**Comment by luvsuck** [comment]
是不是把所有的http://mvnrepo.rokid-inc.com/改成 https://maven.rokid.com/ 就可以了，后面的资源路径还需要更改吗。

**Comment by luvsuck** [comment]
是不是把所有的http://mvnrepo.rokid-inc.com/改成 https://maven.rokid.com/ 就可以了，后面的资源路径还需要更改吗。 @sunchaonew

**Comment by sunchaonew** [comment]
只保留上面一个maven库，将原来的maven库相关的代码：
classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6"
classpath "com.github.dcendents:android-maven-gradle-plugin:1.5"
classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.5.4"
这些都注掉

**Comment by luvsuck** [comment]
注释后，Plugin with id 'rokid-maven' not found。

**Comment by luvsuck** [comment]
注释之后同步结果 Plugin with id 'rokid-maven' not found，这个插件应该是必要的吧

**Comment by luvsuck** [comment]
> 只保留上面一个maven库，将原来的maven库相关的代码：
> classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6"
> classpath "com.github.dcendents:android-maven-gradle-plugin:1.5"
> classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.5.4"
> 这些都注掉

注释之后同步结果 Plugin with id 'rokid-maven' not found，这个插件应该是必要的吧

**Comment by luvsuck** [comment]
> 只保留上面一个maven库，将原来的maven库相关的代码：
> classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6"
> classpath "com.github.dcendents:android-maven-gradle-plugin:1.5"
> classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.5.4"
> 这些都注掉

@sunchaonew 您好 ，注释之后同步结果 Plugin with id 'rokid-maven' not found，这个插件应该是必要的吧

**Comment by sunchaonew** [comment]
这个插件也不需要的，可以注掉

**Comment by luvsuck** [comment]
@是了，rokid maven都去掉可以sync了。感谢。

**Comment by luvsuck** [comment]
是了，rokid maven都去掉可以sync了。感谢。 @sunchaonew

**Comment by sunchaonew** [comment]
不客气
