### ISSUE TITLE
关于rokid glass2实时视频流推流问题

### ISSUE THREAD

**Issue by luvsuck** [RokidGlass/glass2-docs#191]
glass2+dock开发

请问一下，我们有业务需要实时视频推流，对于这个使用场景我看到官网和当时产品的介绍中都有在线视频会议的这种案例，基于这个业务场景我想咨询以下两点问题。

1. 购买三方服务，rokid提供什么在线视频流服务么(免费或收费的)。

2. 如果自己搭建视频流平台的话，我目前考虑是使用node.js+ffmpeg的方式将rokid相机数据传输过去，请问有什么更好的技术选型上的实施建议么。

感谢！

**Comment by yeungeek** [comment]
1. 视频会议服务，可以选择很多市面上成熟的产品，譬如腾讯会议，声网等
2. 如果自己搭建音视频服务，建议使用基于 webrtc 的方案。相机数据编码传输的方式，可以直接使用 Android的 mediacodec 或者 ffmpeg

**Comment by luvsuck** [comment]
@yeungeek 感谢。另外想问一下，在rokid galss2+dock 如何调用扫码 以及扫码相关的回调，以及我想咨询一下，在线asr是可以实时解析语音成文字，还是只能预设好文本作为指令，然后解析出来啊？

**Comment by luvsuck** [comment]
@yeungeek  感谢您的回复，确实帮到了我们很多。
另外想问一下，在rokid galss2+dock开发中还有下面几个问题：
1. asr问题：官方提供的在线asr是可以解析实时语音转成文字，还是只能预设好文本作为指令，然后解析出来。
2. 录音问题：另外如果想要调用录音，是直接使用安卓的录音api就可以，还是要使用rokid提供的些什么来实现。
3. 使用dock还是手机进行开发，到底有什么本质区别，我理解是系统不一样，dock是用的rokid做的基于android的yodaos，手机的话就是android os，两者开发apk的过程中有些许不同，这只是基于开发的角度的区别，然而最关键的是业务的角度，在各中业务场景中，什么场景下适合用手机，什么场景下适合用dock，您能站在程序员的角度上讲一下么，感谢您。

**Comment by yeungeek** [comment]
@luvsuck 
1. 关于asr的问题，请参考我们开放平台的文档，https://rokid.yuque.com/books/share/7b325232-3dae-4ed2-8821-93f915d1ef95/xcrv0k
2. 这个可以直接使用Android的标准API
3. 关于系统的区别，建议参考我们开放平台的相关文档，https://rokid.yuque.com/books/share/7b325232-3dae-4ed2-8821-93f915d1ef95/xcrv0k

最后，也非常感谢对我们开放平台的关注
