### ISSUE TITLE
如何获取扫码的解析内容

### ISSUE THREAD

**Issue by luvsuck** [RokidGlass/glass2-docs#194]
您好，使用rokid glass+dock开发 ，调起扫码后如何获取解析内容。文档中写从 com.blikoon.qrcodescanner.got_qr_scan_relult 中获取，具体是怎么获取啊。

**Comment by luvsuck** [comment]
文档中 this.startActivityForResult(intent, REQUEST_CODE_QR_SCAN_WIFI);

**Comment by luvsuck** [comment]
您好，但是扫码后立马就toast出结果，但是onActivityResult中获取到的data为null ，resultCode为0。
@DylanWang2020

**Comment by luvsuck** [comment]
谢谢，解决了，我用了com.rokid.glass.scan2.ScanActivity这个，这个是直接把结果弹窗出来的没有传给intent

**Comment by luvsuck** [comment]
谢谢您，解决了，我用了com.rokid.glass.scan2.ScanActivity这个，这个是直接把结果弹窗出来的没有传给intent
@DylanWang2020

**Comment by DylanWang2020** [comment]
具体是怎么使用的，能贴下代码或者详细描述下吗？

**Comment by luvsuck** [comment]
`public class MainActivity extends AppCompatActivity {
    private GlassButton btn;

    private SpeechUserManager speechUserManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        //1.初始化speechUserManager，并且立即绑定
        speechUserManager = new SpeechUserManager(this, true);
        btn = findViewById(R.id.btn_2);
        btn.setOnClickListener(v -> {
            //asr
            speechUserManager.doSpeechAsr(asrCallBack);
        });

    }

    private AsrCallBack asrCallBack = new AsrCallBack() {
        @Override
        public void onStart(int id) throws RemoteException {
            System.out.println("asr onstart:  " + id);
        }

        @Override
        public void onIntermediateResult(int id, String s1, String s2) throws RemoteException {
            System.out.println("asr onIntermediateResult  " + id + " | " + s1 + " | " + s2);
        }

        @Override
        public void onAsrComplete(int id, String s) throws RemoteException {
            System.out.println("asr onAsrComplete" + id);
        }

        @Override
        public void onComplete(int i, String s, String s1) throws RemoteException {
            System.out.println("complete");
        }

        @Override
        public void onCancel(int i) throws RemoteException {
            System.out.println("cancel");
        }

        @Override
        public void onError(int i, int i1) throws RemoteException {
            System.out.println("onError:" + i + ":" + i1);

        }
    };

}`

**Comment by luvsuck** [comment]
您好 代码贴在上面了 @DylanWang2020

**Comment by WanderingGavin** [comment]
@luvsuck  可以logcat搜索一下 speech 日志，执行并上传一下

**Comment by luvsuck** [comment]
看了下日志应该是网络或者地质问题吧 10-11 13:22:07.657  4229  4248 I rokid.Connection.speech: recv: failed, connection broken

**Comment by WanderingGavin** [comment]
@luvsuck asr功能有使用成功过吗，目前设备是在什么地方请求服务器。asr是在线功能，需要先联通rokid asr 云服务器。

**Comment by luvsuck** [comment]
@WanderingGavin 好的谢谢
