### ISSUE TITLE
使用imu sdk报错，Failed to call observer method

### ISSUE THREAD

**Issue by luvsuck** [RokidGlass/glass2-docs#195]
rokid glass2+dock
您好，在使用imu sdk过程中，报错如下（组织名用*号替代了）
java.lang.RuntimeException: Unable to resume activity {com.*.*/com.*.*.IMUActivity}: java.lang.RuntimeException: Failed to call observer method
....
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.app.Application.getContentResolver()' on a null object reference

----

catlog查看日志里面有一个npe异常  
10-13 10:48:00.467 17354 17354 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.app.Application.getContentResolver()' on a null object reference

**Comment by luvsuck** [comment]
使用官方uidemo中 imu 是可以正常使用的，转到android X 项目中就会报错，不知道上不是android x的问题

**Comment by iles-Chester** [comment]
估計是少了IMUSdk.init(this);
