### ISSUE TITLE
Rokid Air display issue

### ISSUE THREAD

**Issue by flashbits** [RokidGlass/glass2-docs#197]
Hello,
I have installed Rokid Air App on my Samsung S10,
then I connect Rokid Glasses and I see this picture inside:
![rokid_air_issue](https://user-images.githubusercontent.com/42935822/138486220-eb478c74-0fdf-4f06-a1bc-a9dd5d5370ca.jpg)
There are two rects:
top left corner - half screen of something;
bottom rect - just a noise.

Samsung DeX works fine with Rokid Glasses.

**Comment by youneonsik** [comment]
hello. I have a question.
I started the Rokid Air app and built and ran the RokidUXR_Sample_Unity_ForPhone. It doesn't work when I run HeadTracking in the app's scene. What is the way for HeadTracking to work?

thank you.

**Comment by ghost** [comment]
I had the same issue with my galaxy note 10+. My workaround was to disable Samsung DEX in the Phone-Settings. Now it works just fine

**Comment by yuyunjing** [comment]
The developer forum address has changed. Please go to the new forum to ask questions. We will respond to your questions in time. The new address is: https://forum.rokid.com/
