### ISSUE TITLE
Regarding the broken link 

### ISSUE THREAD

**Issue by dietapp2020** [RokidGlass/glass2-docs#45]
Dear Team , The glass 2 projects which are using these links are not working.
1) http://mvnrepo.rokid-inc.com/nexus/content/groups/public/' 
2) http://mvnrepo.rokid-inc.com/nexus/content/repositories/releases/

Please provide me the updated links so i can run the projects on the glass

**Comment by yeungeek** [comment]
@dietapp2020 
This is the internal maven repository.
which github repo declarative this dependency?
We will check, if it is necessary
