### ISSUE TITLE
Problems accessing camera via UVC

### ISSUE THREAD

**Issue by dilldilldill** [RokidGlass/glass2-docs#54]
I am having trouble reliably accessing the camera via UVC when having it plugged in into my Samsung Galaxy A90 running on Android 10. Whenever accessing the camera it detaches itself within a couple of seconds and attaches again. The problem is also reproducable with the second app from the top of Google PlayStore when searching for 'uvc' (USB Camera - Connect EasyCap).

My solution which is based on the UVCCamera lib (https://github.com/saki4510t/UVCCamera) as well as the top two apps on the screenshot are working flawlessly (plug and play) with the nreal, mad gaze glasses and USB webcams but not with the rokid glass.

The other problem I came across was that the mirrored image which appears in the glass when plugging it into an android device seems to be distorted.

I hope that it's possible to reproduce this on other devices using the rokid glass.

Thanks in advance

**Comment by PuppiesMeat** [comment]
@dilldilldill 
We're using glasses to connect Android's mobile phone only to determine that Huawei Mate is supported, and other types have not yet been validated for the time being. If it's convenient, please provide the types of mobile phone you might use like Samsung A90, and we will evaluate whether we support it. Of course, if you have HuaWei Mate  phone, you can try it

Also we found a problem when using Huawei Mate30, and there might be a shortage of power in usb, so you can try to replace other data lines.

**Comment by lgua9225** [comment]
we just now tested the glasses with a Huawei P30. Everything works as intended with this device, no errors whatsoever.
Errors we encountered using Samsung A90 were:
- As soon as the glasses are plugged into the device everything on the device seems to slow down quite remarkably (UI begins to lag, on the OS side … not even in our application)
- The image in the glasses’ display is broken/faulty
How do we proceed from here? How can we eliminate those problems? We are aiming to cover all modern devices, not just individual devices. Our customers are supposed to choose any modern Android device they want.
Thank you for your help!

**Comment by shiwf** [comment]
> we just now tested the glasses with a Huawei P30. Everything works as intended with this device, no errors whatsoever.
> Errors we encountered using Samsung A90 were:
> 
> * As soon as the glasses are plugged into the device everything on the device seems to slow down quite remarkably (UI begins to lag, on the OS side … not even in our application)
> * The image in the glasses’ display is broken/faulty
>   How do we proceed from here? How can we eliminate those problems? We are aiming to cover all modern devices, not just individual devices. Our customers are supposed to choose any modern Android device they want.
>   Thank you for your help!

Only several mobile phones are supported. Currently, the ones that can be verified include Huawei Mate10, Mate20, and Mate30. Other mobile phones are not recommended. Or you can buy our second-generation glasses + Dock from the seller.
