### ISSUE TITLE
Technical Questions

### ISSUE THREAD

**Issue by lgua9225** [RokidGlass/glass2-docs#56]
Technical questions if I use my android device with the glasses:

- Projector:
  - Image of the projector is faulty
  - Resolution

- Audio:
  - Why is there mono audio only?
  - Echo cancellation?

- Peripheral devices
  - Reaching the sensors (serial connection without additional SDK possible?)  
  - Touchpads (left and right temple)?

**Comment by Machaojoy** [comment]
Hi lgua9225

**Comment by Machaojoy** [comment]
> Technical questions if I use my android device with the glasses:
> 
> * Projector:
>   
>   * Image of the projector is faulty
>   * Resolution
> * Audio:
>   
>   * Why is there mono audio only?
>   * Echo cancellation?
> * Peripheral devices
>   
>   * Reaching the sensors (serial connection without additional SDK possible?)
>   * Touchpads (left and right temple)?

Hi Igua,

**Comment by Machaojoy** [comment]
Hi Igua,
1. Projector:

**Comment by Machaojoy** [comment]
Hi Igua
1. Could you describe the issue about Projector ASAP？

**Comment by Machaojoy** [comment]
Hi Igua

1. Projector：
Could you describe the issue about Projector‘s falut ASAP？
As i know，the resolution of projector is 1280*720.

2. Audio：
mono audio： Glass has only one speaker，but system could use stereo audio
Echo cancellation： not supported

**Comment by Machaojoy** [comment]
3. Peripheral devices
- Reaching the sensors

**Comment by Machaojoy** [comment]
3. Peripheral devices
- Reaching the sensors
 sensor datas are transferred via usb hid，the SDK is here：
https://rokidglass.github.io/glass2-docs/zh/7-glassmobile/res/mobile_glass/glass_hw.html
But now it is written in Chinese，on the road in English。

- Touchpads
Yes，it is also supported in the url above
