### ISSUE TITLE
1、凝视功能(类似文件管理，选择文件的交互模式)，sdk是否有标准控件 2、无限屏功能(类似眼镜相机图片预览功能)，sdk是否有标准控件

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#57]

**Comment by jerrywjj** [comment]
你好，目前暂时没有提供凝视和无限屏的sdk或标准控件，如果想实现类似效果，可以使用开发者网站上的IMU View 控件，或者使用安卓标准的gvr sdk。

**Comment by kaojin-alt** [comment]
IMU View 控件有无限屏和凝视功能吗？

**Comment by jerrywjj** [comment]
目前没有释放，具体可以参考开发者网站里的 https://rokidglass.github.io/glass2-docs/zh/2-sdk/5-ui-sdk/

**Comment by kaojin-alt** [comment]
能开放凝视和无限屏的部分代码吗

**Comment by shiwf** [comment]
> 能开放凝视和无限屏的部分代码吗

你好，凝视功能和无限屏的SDK还在内部调试中，功能尚不完善，未达到释放标准。后续验证通过后将统一释放。

**Comment by kaojin-alt** [comment]
凝视和无限屏功能大概什么时候能释放出来？

**Comment by shiwf** [comment]
> 凝视和无限屏功能大概什么时候能释放出来？

暂无具计划体释放时间点。

**Comment by shiwf** [comment]
> 凝视和无限屏功能大概什么时候能释放出来？

暂无具体释放时间点。

**Comment by shiwf** [comment]
> 凝视和无限屏功能大概什么时候能释放出来？

这个暂无具体计划时间点，如果需要深入合作，欢迎联系商务。

**Comment by kaojin-alt** [comment]
眼镜有补光灯吗

**Comment by shiwf** [comment]
> 眼镜有补光灯吗

眼镜没有配备补光灯
