### ISSUE TITLE
how to use the bluetooth

### ISSUE THREAD

**Issue by lgua9225** [RokidGlass/glass2-docs#58]
hi, how to use bluetooth on my RG201?

**Comment by shiwf** [comment]
In settings->Connections->Bluetooth->Other devices, you can discover bluetooth devices, we can only discover **bluetooth headphone** now. But our glass can be discovered and paired by other bluetooth devices, such as phone and PC. After paired with other devices, you can use the bluetooth the same way as common Android phones.
