### ISSUE TITLE
可以做到点击下面底部栏的按钮，切换fragment么？

### ISSUE THREAD

**Issue by lh414035210** [RokidGlass/glass2-docs#59]
![image](https://user-images.githubusercontent.com/24253339/93316019-45be9480-f83e-11ea-8ab4-253f2935a1ab.png)

如图中所示，可以做到类似于点击下面底部栏的按钮，切换fragment么

**Comment by shiwf** [comment]
> ![image](https://user-images.githubusercontent.com/24253339/93316019-45be9480-f83e-11ea-8ab4-253f2935a1ab.png)
> 
> 如图中所示，可以做到类似于点击下面底部栏的按钮，切换fragment么

glass上不支持触摸，只有touchpad和back按键，只能通过滑动touchpad控制焦点的移动，UI上需要拦截相应的按键事件，并做好焦点的管理。当焦点移到底部栏的按钮上，点击tp应该可以做到切换fragment，这块与原生android并无差异。

**Comment by lh414035210** [comment]
也就是说处理起来有些麻烦对么，  如果想开发一些内容，最好只有竖向的列表，不要间杂着横向内容是么

**Comment by shiwf** [comment]
> 也就是说处理起来有些麻烦对么， 如果想开发一些内容，最好只有竖向的列表，不要间杂着横向内容是么

因为touchpad是一维的，只能发送“前后”，或者“上下”的事件，因此在UI排布上，最好也是一维的，横向或者竖向都可以。如果排布成二维的，则不太方便使用touchpad进行控制。这种情况可以考虑接入语音的SDK，使用语音进行操作。

**Comment by lh414035210** [comment]
是使用贵公司提供的SDK，还是自己接入语音SDK 呢？  感觉使用自己接入的SDK 更加简单些

**Comment by shiwf** [comment]
> 是使用贵公司提供的SDK，还是自己接入语音SDK 呢？ 感觉使用自己接入的SDK 更加简单些

我们有提供离线的语音SDK，接入方法请参考：

**Comment by shiwf** [comment]
> 是使用贵公司提供的SDK，还是自己接入语音SDK 呢？ 感觉使用自己接入的SDK 更加简单些

我们有提供离线的语音SDK，接入方法请参考：
https://rokidglass.github.io/glass2-docs/zh/2-sdk/3-voice-sdk/InstructSdk/InstructSdk.html
