### ISSUE TITLE
How/Where to get SDKs for testing?

### ISSUE THREAD

**Issue by effranco** [RokidGlass/glass2-docs#61]
I'm searching in the RokidGlass repositories, but I couldn't find the SDK for downloading.

I was only able to find the docs and some samples. Where can I find them?

Thanks, effranco.

**Comment by yeungeek** [comment]
@effranco 
We are now using JCenter，There is currently no separate aar download.
example Glass UI SDK dependency, you can use gradle:
`implementation 'com.rokid.glass:ui:1.5.4'`

**Comment by effranco** [comment]
It worked. Thanks.

**Comment by yeungeek** [comment]
Thank you very much for using our company's products. If you have any questions, please give feedback in time
