### ISSUE TITLE
运动跟踪、环境理解功能是否需要借助第三方sdk？

### ISSUE THREAD

**Issue by JobssSoong** [RokidGlass/glass2-docs#62]
我发现官方提供的文档中没有环境的检测和跟踪的介绍，是否需要借助第三方sdk来实现这些功能？

**Comment by shiwf** [comment]
> 我发现官方提供的文档中没有环境的检测和跟踪的介绍，是否需要借助第三方sdk来实现这些功能？

你好，暂时没有提供环境理解与运动跟踪的相关功能及SDK。

**Comment by JobssSoong** [comment]
> > 我发现官方提供的文档中没有环境的检测和跟踪的介绍，是否需要借助第三方sdk来实现这些功能？
> 
> 你好，暂时没有提供环境理解与运动跟踪的相关功能及SDK。

您好，麻烦再问下眼镜是否可以借助Easy AR等SDK进行开发

**Comment by shiwf** [comment]
> > > 我发现官方提供的文档中没有环境的检测和跟踪的介绍，是否需要借助第三方sdk来实现这些功能？
> > 
> > 
> > 你好，暂时没有提供环境理解与运动跟踪的相关功能及SDK。
> 
> 您好，麻烦再问下眼镜是否可以借助Easy AR等SDK进行开发

您好，眼镜的摄像头数据及IMU数据，并未针对VIO类算法进行专门优化，并且CPU算力有限，跑第三方的VIO算法并不能保证良好的体验效果。
