### ISSUE TITLE
关于IMUView

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#66]
有没有IMUView使用的demo可以提供给我

**Comment by yeungeek** [comment]
@kaojin-alt 在 [glass-ui](https://github.com/RokidGlass/glass-ui/tree/develop) 库中有对应的 [demo](https://github.com/RokidGlass/glass-ui/blob/develop/demo/src/main/java/com/rokid/glass/ui/sample/IMUActivity.java)
