### ISSUE TITLE
关于指令

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#67]
添加指令后，眼镜屏幕最下方会将所有添加的指令都显示出来，如何让眼镜下方的指令不显示

**Comment by WanderingGavin** [comment]
相关设置在语音指令的文档中有详细说明，在指令创建的时候：
1. 可以通过setShowTips(boolean showTips)来设置指令在屏幕tips条上是否展示；
2. 可以通过setIgnoreHelp(boolean ignoreHelp)来设置指令在帮助浮层上是否展示；
默认未设置的情况，指令在屏幕tips条上不展示，在帮助浮层上展示。
eg：
new InstructEntity()
                                .addEntityKey(new EntityKey("进入视频", null))
                                .addEntityKey(new EntityKey(EntityKey.Language.en, "open video"))
                                .setShowTips(true)
                                .setIgnoreHelp(true)
                                .setCallback(new IInstructReceiver() {
                                    @Override
                                    public void onInstructReceive(Activity act, String key, InstructEntity instruct) {
                        
                                    }
                                }
