### ISSUE TITLE
目前有没有Unity的离线语音SDK

### ISSUE THREAD

**Issue by a1228267639** [RokidGlass/glass2-docs#69]

**Comment by a1228267639** [comment]
看了一下都是 基于Andorid开发的Demo  能提供Unity3d的语音Demo吗

**Comment by jerrywjj** [comment]
你好，目前暂时没有开放Unity3D的语音插件。

**Comment by a1228267639** [comment]
好的, WIFI打开的情况下 为什么连接不上无线网呢？

**Comment by sunchaonew** [comment]
连接wifi是通过扫一扫扫描对应的联网二维码进行连接的，你是扫码连接不上吗？连接不上有什么提示吗

**Comment by a1228267639** [comment]
哦，那是我操作有问题。 目前安装应用到眼镜上 有几种方式呢？

**Comment by jerrywjj** [comment]
开发者可以直接通过adb安装apk

**Comment by a1228267639** [comment]
请问有Unity3d 接 离线语音的 文档 或者例子吗

**Comment by jerrywjj** [comment]
目前还没对外发布，你可以留一下你的邮箱，我们技术人员可以帮助你使用。

**Comment by a1228267639** [comment]
好的谢谢   1228267639@qq.com

**Comment by a1228267639** [comment]
能提供 技术的联系方式 我想咨询一些问题。

**Comment by XRWorld17** [comment]
> 能提供 技术的联系方式 我想咨询一些问题。



> 请问有Unity3d 接 离线语音的 文档 或者例子吗

相关链接已发送邮箱，请查收

**Comment by a1228267639** [comment]
我刚才打开 好像是404 是怎么回事。

**Comment by a1228267639** [comment]
好的 看到了。
