### ISSUE TITLE
关于离线指令

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#70]
只有在Activity中的onCreate方法中添加指令才生效吗？
如果在别的方法中添加不能使用吗

**Comment by kaojin-alt** [comment]
眼镜界面最下方的返回上一级  和显示帮助 指令  如何取消获取隐藏起来

**Comment by WanderingGavin** [comment]
1. 指令初始化推荐放在onCreate方法中，这个生命周期只会被调用一次，不会对指令插件SDK内代码进行干扰。指令集合会在onResume()时自动设置到系统语音助手中，其他时间需要手动设置指令生效需要调用InstructLifeManager/InstructionManager 的 sendWtWords()方法；
2. 界面下方的指令tips提示条可以整体隐藏：（需要在onStart()周期后，推荐在onTipsUiReady()回调中操作）
    InstructLifeManager/InstructionManager 的 hideTipsLayer()方法用来隐藏整体tips提示条，
    InstructLifeManager/InstructionManager 的 setLeftBackShowing(boolean showing) 来控制tips浮条左侧“返回上一级”显隐，
    “显示帮助”目前只能随tips一起显隐，不能单独控制。
