### ISSUE TITLE
眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?

### ISSUE THREAD

**Issue by wydin** [RokidGlass/glass2-docs#71]
眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?
如果可以的话怎么安装？

**Comment by shiwf** [comment]
> 眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?
> 如果可以的话怎么安装？

您好，关于输入法，因为眼镜上TP操作的特点，没有第三方输入法能够完美的适配，即使安装也无法使用，因此我们的设置中没有增加安装并设置第三方输入法的功能；
关于蓝牙键盘，因为我们的使用场景中没有外接蓝牙键盘的需求，因此设置中的蓝牙连接，并不能连接蓝牙键盘。不过眼镜本身是可以支持蓝牙键盘的，您可以自行开发蓝牙发现并连接的APP来连接蓝牙键盘；
另外，您也可以使用命令“adb shell am start com.android.settings”打开安卓原生的设置，在原生设置中进行蓝牙搜索配对，以及设置输入法。

**Comment by wydin** [comment]
> > 眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?
> > 如果可以的话怎么安装？
> 
> 您好，关于输入法，因为眼镜上TP操作的特点，没有第三方输入法能够完美的适配，即使安装也无法使用，因此我们的设置中没有增加安装并设置第三方输入法的功能；
> 关于蓝牙键盘，因为我们的使用场景中没有外接蓝牙键盘的需求，因此设置中的蓝牙连接，并不能连接蓝牙键盘。不过眼镜本身是可以支持蓝牙键盘的，您可以自行开发蓝牙发现并连接的APP来连接蓝牙键盘；
> 另外，您也可以使用命令“adb shell am start com.android.settings”打开安卓原生的设置，在原生设置中进行蓝牙搜索配对，以及设置输入法。

如果 想进行一些简单的收入，例如 设备度数 或者 设备型号之类，你们有什么好的录入方案吗？

**Comment by shiwf** [comment]
> > > 眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?
> > > 如果可以的话怎么安装？
> > 
> > 
> > 您好，关于输入法，因为眼镜上TP操作的特点，没有第三方输入法能够完美的适配，即使安装也无法使用，因此我们的设置中没有增加安装并设置第三方输入法的功能；
> > 关于蓝牙键盘，因为我们的使用场景中没有外接蓝牙键盘的需求，因此设置中的蓝牙连接，并不能连接蓝牙键盘。不过眼镜本身是可以支持蓝牙键盘的，您可以自行开发蓝牙发现并连接的APP来连接蓝牙键盘；
> > 另外，您也可以使用命令“adb shell am start com.android.settings”打开安卓原生的设置，在原生设置中进行蓝牙搜索配对，以及设置输入法。
> 
> 如果 想进行一些简单的输入，例如 设备度数 或者 设备型号之类，你们有什么好的录入方案吗？

我们自带的输入法，支持输入大小写英文、数字和常见符号，看下是否可以满足你的需求

**Comment by wydin** [comment]
> > > > 眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?
> > > > 如果可以的话怎么安装？
> > > 
> > > 
> > > 您好，关于输入法，因为眼镜上TP操作的特点，没有第三方输入法能够完美的适配，即使安装也无法使用，因此我们的设置中没有增加安装并设置第三方输入法的功能；
> > > 关于蓝牙键盘，因为我们的使用场景中没有外接蓝牙键盘的需求，因此设置中的蓝牙连接，并不能连接蓝牙键盘。不过眼镜本身是可以支持蓝牙键盘的，您可以自行开发蓝牙发现并连接的APP来连接蓝牙键盘；
> > > 另外，您也可以使用命令“adb shell am start com.android.settings”打开安卓原生的设置，在原生设置中进行蓝牙搜索配对，以及设置输入法。
> > 
> > 
> > 如果 想进行一些简单的输入，例如 设备度数 或者 设备型号之类，你们有什么好的录入方案吗？
> 
> 我们自带的输入法，支持输入大小写英文、数字和常见符号，看下是否可以满足你的需求

不是，很好用哈，能语音输入吗？

**Comment by shiwf** [comment]
> > > > > 眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?
> > > > > 如果可以的话怎么安装？
> > > > 
> > > > 
> > > > 您好，关于输入法，因为眼镜上TP操作的特点，没有第三方输入法能够完美的适配，即使安装也无法使用，因此我们的设置中没有增加安装并设置第三方输入法的功能；
> > > > 关于蓝牙键盘，因为我们的使用场景中没有外接蓝牙键盘的需求，因此设置中的蓝牙连接，并不能连接蓝牙键盘。不过眼镜本身是可以支持蓝牙键盘的，您可以自行开发蓝牙发现并连接的APP来连接蓝牙键盘；
> > > > 另外，您也可以使用命令“adb shell am start com.android.settings”打开安卓原生的设置，在原生设置中进行蓝牙搜索配对，以及设置输入法。
> > > 
> > > 
> > > 如果 想进行一些简单的输入，例如 设备度数 或者 设备型号之类，你们有什么好的录入方案吗？
> > 
> > 
> > 我们自带的输入法，支持输入大小写英文、数字和常见符号，看下是否可以满足你的需求
> 
> 不是，很好用哈，能语音输入吗？

抱歉，没有语音输入法的功能

**Comment by wydin** [comment]
> > > > > > 眼镜可以安装第三方输入法吗？能不能连接蓝牙键盘?
> > > > > > 如果可以的话怎么安装？
> > > > > 
> > > > > 
> > > > > 您好，关于输入法，因为眼镜上TP操作的特点，没有第三方输入法能够完美的适配，即使安装也无法使用，因此我们的设置中没有增加安装并设置第三方输入法的功能；
> > > > > 关于蓝牙键盘，因为我们的使用场景中没有外接蓝牙键盘的需求，因此设置中的蓝牙连接，并不能连接蓝牙键盘。不过眼镜本身是可以支持蓝牙键盘的，您可以自行开发蓝牙发现并连接的APP来连接蓝牙键盘；
> > > > > 另外，您也可以使用命令“adb shell am start com.android.settings”打开安卓原生的设置，在原生设置中进行蓝牙搜索配对，以及设置输入法。
> > > > 
> > > > 
> > > > 如果 想进行一些简单的输入，例如 设备度数 或者 设备型号之类，你们有什么好的录入方案吗？
> > > 
> > > 
> > > 我们自带的输入法，支持输入大小写英文、数字和常见符号，看下是否可以满足你的需求
> > 
> > 
> > 不是，很好用哈，能语音输入吗？
> 
> 抱歉，没有语音输入法的功能

再了解一下哈，咱们眼镜蓝牙耳机是不是能连接？

**Comment by shiwf** [comment]
可以连接蓝牙耳机，在设置 连接设置 蓝牙中，可以搜索到并连接上蓝牙耳机
