### ISSUE TITLE
关于ImuView

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#72]
ImuView左上角的数字角标  如何显示

**Comment by kaojin-alt** [comment]
赶紧回复呀

**Comment by sunchaonew** [comment]
你好，在glass二代设备的：系统设置-控制中心-全语音模式，打开语音开关，集成此控件会自动在左上角显示数字角标

**Comment by kaojin-alt** [comment]
我打开了这个开关   还是没有左上角的数字

**Comment by sunchaonew** [comment]
可以参考demo中IMUActivity的调用方法。还有问题的话请把调用的代码贴一下吧
