### ISSUE TITLE
关于离线指令

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#73]
A页面和B页面都有指令
A页面跳转到B页面，A页面未finish
当后台动态改变A页面的指令时会影响B页面的指令
如何解决

**Comment by WanderingGavin** [comment]
Glass XR OS 系统在同一时间，只会有一组语音指令集合生效。即当B页面指令生效，A页面指令会被覆盖掉，同理，B页面在顶端，A页面设置了指令集合，那当前B页面指令集合会被A页面新设置的指令集合覆盖掉。
运用语音插件设置语音指令集合分为两种状态：
1. 指令在App 指令插件中设置：
2. 由指令插件将指令集合设置到系统语音助手中；
上述问题解决方案：
后台动态改变A页面的指令时只改变A页面指令插件中的集合内容，不要继续设置到系统语音助手中，即不要调用sendWtWords()方法。
当A页面变化到系统显示最上层时，语音指令插件会自动将插件内的指令集合设置到系统语音助手中。
注意：要保证A、B两个页面的ActionKey不相同。
