### ISSUE TITLE
Camera library & QRCode scanning

### ISSUE THREAD

**Issue by effranco** [RokidGlass/glass2-docs#74]
We are developing a glass app using the usb video cam for access control (i.e., by scanning QRCodes).

We found in "RokidGlass" Github, especially  the "RokidFaceSDK",  some examples of using the "DefaultCameraView".

I saw that there is a package for dealing with the glass camera (i.e., "com.rokid.camerakit"). Is there a "javadoc" describing it?

For recognizing the QRCodes and other barcodes, is there some specific designed for the glass or shall I use the "Android's Barcode API"?

https://developers.google.com/ml-kit/vision/barcode-scanning

Thanks in advance.

**Comment by zvlwwj** [comment]
the "DefaultCameraView" is based on standard android lib. no specific designed for the glass.if you want to implement QRCode scanning, you can choose the  standard android lib(camera camera2).

**Comment by effranco** [comment]
Thanks for the quick response.

Is there some Rokid's library specific for QRCode scanning or shall I use the Android Barcode API ?

**Comment by zvlwwj** [comment]
we use zxing for QRCode https://github.com/zxing/zxing.
we have not used Android Barcode API, you can try it.

**Comment by effranco** [comment]
Thanks for the help.
