### ISSUE TITLE
关于眼镜问题

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#76]
1、正常视频录制一直失败，是否能提供一下视频录制的demo
2、动态添加语音指令会有延迟或者卡顿，比如我动态添加了几个指令，说了很多遍都没有识别，过了几秒或者十几 
      秒，之前说的指令会重复识别很多次。有时候还会出现语音模块崩溃的提示，如何解决
3、眼镜摄像头是否内置了自动对焦功能，我使用相机拍摄或者推流一直在自动对焦

**Comment by yeungeek** [comment]
1. 目前我们相机的录像，使用的标准录制 API，MediaRecorder+Camera2
2. 动态添加指令，可以参考下离线语音接入文档，离线语音词要效果比较好，需要进行训练，建议使用四个字语音词
在 logcat中过滤 audioai，查看语音的日志
3. 眼镜端摄像默认是定焦的，应用可以通过 Camera 标准 api 进行对焦模式的切换

**Comment by WanderingGavin** [comment]
正常动态添加语音指令不会有超过1秒的延迟，但还是不推荐动态添加大量普通指令或数字指令，如个数超过100，大量添加会导致略微延迟，但不会超过2秒。
根绝你的情况分析，应该是APP运行时占用大量CPU，导致语音算法运行不畅，没有CPU资源进行识别运算，识别被长时间延迟压制。
