### ISSUE TITLE
关于眼镜摄像头调用的问题

### ISSUE THREAD

**Issue by zhaoshichao** [RokidGlass/glass2-docs#77]
1、请求相机权限，运行程序，没有展示授权界面
2、使用相机功能，闪退报错：java.lang.RuntimeException: Unknown camera ID

是否需要做什么特殊处理才能调用眼镜的摄像头？

**Comment by shiwf** [comment]
> 1、请求相机权限，运行程序，没有展示授权界面
> 2、使用相机功能，闪退报错：java.lang.RuntimeException: Unknown camera ID
> 
> 是否需要做什么特殊处理才能调用眼镜的摄像头？

1. 我们设备默认跳过动态权限检查，只要在xml里静态申请权限即可；
2. 我们相机的LENS_FACING属性为LENS_FACING_BACK（1），cameraId是0，请确认是否开启的正确的CameraId，可参考官方demo：https://github.com/googlearchive/android-Camera2Basic

**Comment by zhaoshichao** [comment]
感谢回复
