### ISSUE TITLE
Inquiry on Rokid Glass II

### ISSUE THREAD

**Issue by mabh96** [RokidGlass/glass2-docs#79]
1. When using RemoteExpert, person with the glass unable to see the support engineer on the other end.

2. Unable to transfer PDF document using phone (Remote Glass II app).

3. Unable to connect the Rokid glass to the PC.

4. Support engineer cant give live indication based on the view of the glass (Have to take snapshot of the view from the glass and give the indication based on the snapshot).

5. Cant zoom in and out by using the touch pad.

6. When using RemoteExpert image produced from the glass is shaky and the quality quite poor.

**Comment by yeungeek** [comment]
1.  Currently we can see the local camera preview, The next version provides video wall 
2. does not support sharing of other files(except for pictures)
3. Are you connected correctly (use type-c), we all use adb connection pc
4. 5 Later will support
6. update the system version >= 1.2.6，has improved a lot
