### ISSUE TITLE
关于ndk类型问题

### ISSUE THREAD

**Issue by zhaoshichao** [RokidGlass/glass2-docs#81]
请问下眼镜的硬件架构类型是哪种啊？
这边尝试了'armeabi-v7a', 'arm64-v8a'  还是提示：
Compatible side by side NDK version was not found. Default is 21.0.6113669.
谢谢

**Comment by shiwf** [comment]
你好，眼镜android是32位（v7a），这个错误应该跟硬件没关系，是AS的NDK version没有下载。
tools–>sdk manager–>Android sdk–>SDK Tools–>勾上右下角Show Package Detail–>找到NDK(side by side) ，下载21.0.6113669即可

**Comment by Machaojoy** [comment]
> 请问下眼镜的硬件架构类型是哪种啊？
> 这边尝试了'armeabi-v7a', 'arm64-v8a' 还是提示：
> Compatible side by side NDK version was not found. Default is 21.0.6113669.
> 谢谢

硬件是ARMv8，内核是64位，Android是32位。

**Comment by zhaoshichao** [comment]
> 你好，眼镜android是32位（v7a），这个错误应该跟硬件没关系，是AS的NDK版本没有下载。
> 工具–> sdk管理器–> Android sdk–> SDK工具–>勾上右下角显示软件包详细信息– >找到NDK（并排），下载21.0.6113669即可

我尝试下 谢谢

**Comment by zhaoshichao** [comment]
> > 这边
> > 尝试了'armeabi-v7a'，'arm64-v8a'还是提示：
> > 未找到兼容的并行NDK版本。默认值为21.0.6113669。
> > 谢谢
> 
> 硬件是ARMv8，内核是64位，Android是32位。

收到  谢谢

**Comment by zhaoshichao** [comment]
> > 这边
> > 尝试了'armeabi-v7a'，'arm64-v8a'还是提示：
> > 未找到兼容的并行NDK版本。默认值为21.0.6113669。
> > 谢谢
> 
> 硬件是ARMv8，内核是64位，Android是32位。

**Comment by zhaoshichao** [comment]
> 你好，眼镜android是32位（v7a），这个错误应该跟硬件没关系，是AS的NDK版本没有下载。
> 工具–> sdk管理器–> Android sdk–> SDK工具–>勾上右下角显示软件包详细信息– >找到NDK（并排），下载21.0.6113669即可

按照您说的尝试了下 果然好了 再次感谢
