### ISSUE TITLE
关于离线人脸识别

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#82]
离线人脸识别 
在不影响识别效率的情况下  数据库最多可以放多少张人脸
在不影响识别效率的情况下  最多可以识别到多少个人脸

**Comment by jerrywjj** [comment]
本地数据库最多30万张人脸，由于屏幕限制，同时建议最多识别10人。
你好，方便留一下你的邮箱吗？
我们看到您的需求涉及很广，需要了解您的行业背景，更好的支持。
