### ISSUE TITLE
Problems occuring in accessing UVC camera

### ISSUE THREAD

**Issue by Easteria** [RokidGlass/glass2-docs#83]
Hi, I'm trying to develop the unity app which uses Rokid Glass 2 as a UVC Camera.
And I encountered to some issues like below. Please help me to find this problem.
The app is mainly used to show AR object with Vuforia.

1. When I start the app with connected to glasses, there is a modal which asks me "Allow 'App' to access Kenobi?". If it works alright, it should start the scene. However when I hit 'OK' button, the app doesn't show any responses. After that, I terminate the app completely and start the app again, then I can see the modal which asks me "Allow 'App' to access ROKIDCAM-A901?". In this phase, it works well if I hit 'OK' button. But when I detach the glasses and attach again, the problem occurs again.

2. Is there any way of controlling the light detection to modify the light intensity?

Thanks in advance.

**Comment by PuppiesMeat** [comment]
@Easteria There is two drivers with Rokid Glass 2. One is standard uvc interface and another driver is used to control like light  intensity, and also you can get keyevents、light sensor、distance sensor or imu events

**Comment by Easteria** [comment]
@PuppiesMeat Thanks for your reply. 
I found
RKGlassDevice.getInstance().setBrightness(status ? 100 : 0);
from the document of Rokid Glass 2, and it looks like the control part of light intensity.
But if I change the brightness via that method, can I hold automatic brightness adjustment for a moment?
Because I'm using Vuforia and the object should be displayed about 1~2 mins, but the brightness sometimes disturbs the recognition.

**Comment by PuppiesMeat** [comment]
@Easteria 
At present, we use UVC(https://github.com/jiangdongguo/AndroidUSBCamera) open source library for camera control. I did not find a corresponding interface for automatic brightness adjustment in this open source library, so there is no such interface at present.
