### ISSUE TITLE
关于Rokid 中libuvc.so ，libUVCCamera.so，libusb100.so，libjpeg-turbo1500.so  与我们现有的项目起了冲突

### ISSUE THREAD

**Issue by lh414035210** [RokidGlass/glass2-docs#84]
您好：
     购买了贵公司的Rokid 眼镜后，想适配到我们公司原有项目上。。 但是以上所述的  so 文件与我们现有的起了冲突， 现有的so ，也是一款AR眼镜里面的。。  现在导致无法兼容的情况，请问这种情况该怎么处理

**Comment by lanyuqingri** [comment]
您好，目前我们提供的sdk上是依赖uvc camera，因此默认集成了进去， 您是使用的那个sdk？我们来对应看下是否可以将uvc camera相关的集成剥离一下，另外您这边的使用场景是怎样的？ 我们来看下是否可以采用其他方式来支持？

**Comment by lh414035210** [comment]
我们现在做了一个app ，用了悉见的一副AR眼镜，  现在又购买了贵公司的眼镜，想做到兼容，或者说，以后有更好的产品，也兼容进去。。

**Comment by lh414035210** [comment]
剥离了  uvc camera , 对于贵公司眼镜的控制会有影响么

**Comment by lanyuqingri** [comment]
uvc camera只是获取我们眼镜camera数据的一种方式，如果贵司已经对uvc camera的接口进行了封装，那可以直接使用贵司的uvc camera的代码，对我们眼镜的其他控制不会有影响，当然您那边也可以直接使用我们这边的uvc camera的代码，我们是基于开源的https://github.com/jiangdongguo/AndroidUSBCamera 的代码来进行封装的，使用方法基本都一样，贵司如果直接集成我们的sdk，而之前的uvc camera 没有经过特别的封装的话，之前的接口应该可以直接使用的。

**Comment by lh414035210** [comment]
主要是我们之前的眼镜的代码不是我们写的，也是眼镜厂商封装成sdk  给我们用的，  我们改不了里面内容

**Comment by lanyuqingri** [comment]
贵司这边使用我们眼镜主要使用那些能力？ 使用的sdk是哪个？ 另外我们把uvc camera 剥离掉之后，贵司这边获取我们眼镜的camera数据是否有接口可以使用？

**Comment by lh414035210** [comment]
主要用双屏异显和 一些 控制功能。。  另外也会用到 戴上眼镜与人通话的这种场景

**Comment by lh414035210** [comment]
我们    悉见对 uvccamera做了些封装， 封装成XmanCameraTextureView，  在Android 布局文件中XmanCameraTextureView，然后做些配置，就可以进行眼镜的预览效果了

**Comment by lh414035210** [comment]
或者说，你们打包成的 so 文件，加上自己的命名，能够解决该冲突么？  这样 so 命名不一样， 就检测不出冲突了，两个sdk 是不是就可以兼容了呢

**Comment by lh414035210** [comment]
![image](https://user-images.githubusercontent.com/24253339/99633066-457a8980-2a79-11eb-84d5-f7dc81f7597a.png)
  这个是亮亮科技官网apk， 解压后的 so 文件，都是有自己的命名。。这样是不是就可以避免和其他sdk 冲突呢

**Comment by lanyuqingri** [comment]
OK,我们这边评估一下剥离的方案，同时您这边可以先基于我们的Demo 尝试先去开发一下其他场景的功能，确认好方案以及时间点之后会同步给您

**Comment by lh414035210** [comment]
好的，如果有什么最新的进展麻烦告之我们， 在这里可以，通过李经理转述也行

**Comment by lh414035210** [comment]
hello,早上好啊。。 请问你们的方案出来了么？  大概是怎么样个方式处理这种与其他厂商眼镜冲突呢

**Comment by lanyuqingri** [comment]
您好，我们内部讨论了一下，关于剥离方案，我们初步讨论的设计： 将uvc camera 与我们硬件控制的功能api解耦，这样硬件控制的api 就可以不用依赖uvc camera相关的内容，我们大致会在12.4号左右释放测试通过的sdk 以及对应文档更新。

**Comment by lh414035210** [comment]
如果不解耦的话，有没有其他方式解决这种问题呢？   比如动态加载so 或者什么的

**Comment by lanyuqingri** [comment]
从目前的整体设计上而言，sdk层面没有其他更好的解决方案了，或者咱们这边通过gradle配置，分包处理，根据不同的flavor引用不同的sdk ？

**Comment by hweilong** [comment]
**请问下，怎么可以既显示副屏（副屏上没有UVCCameraTextureView）的同时又得到眼镜画面数据**

**Comment by hweilong** [comment]
**应该是要离屏渲染，SDK上面有支持吗？**

**Comment by PuppiesMeat** [comment]
> **应该是要离屏渲染，SDK上面有支持吗？**

目前SDK没有支持

**Comment by PuppiesMeat** [comment]
@lh414035210 你好 这边单独出了一半剥离uvc的maven库，主要用来获取眼镜的按键、触控事件 
maven依赖方式：    implementation "com.rokid.alliance.hardware:hardware:1.1.9"
使用比较简单 参考RKGlassHardware这个类

**Comment by sky-ins** [comment]
@lanyuqingri  @PuppiesMeat @lh414035210  大佬们麻烦问问冲突这个问题最后是怎么解决的？

**Comment by lanyuqingri** [comment]
之前的解决方案是客户使用他们自己的UVC camera 的库，然后我们这边把uvc camera 和 hardware的sdk进行了剥离，客户只使用我们hardware相关的sdk，获取眼镜的按键/触摸等事件，进行应用开发
