### ISSUE TITLE
Camera数据回调保存照片花屏

### ISSUE THREAD

**Issue by mxmjerry** [RokidGlass/glass2-docs#85]
onPreviewResult 回传的是NV21格式数据嘛？通过 YuvImage转换保存下的照片都是花屏的，这是什么情况？

**Comment by lanyuqingri** [comment]
您那边是设置的AbstractUVCCameraHandler.OnPreViewResultListener 拿到的onPreviewResult 数据回调吗？ 还是通过其他方式？

**Comment by mxmjerry** [comment]
> 您那边是设置的AbstractUVCCameraHandler.OnPreViewResultListener 拿到的onPreviewResult 数据回调吗？ 还是通过其他方式？

是通过AbstractUVCCameraHandler.OnPreViewResultListener这个拿到的数据。

**Comment by lanyuqingri** [comment]
您这边是调用我们这边那个sdk的接口？或者给出具体的调用方式？

**Comment by mxmjerry** [comment]
> 您这边是调用我们这边那个sdk的接口？或者给出具体的调用方式？

用的你们SDK调用的。下载的是你们提供的demo

**Comment by lanyuqingri** [comment]
https://github.com/RokidGlass/RokidGlassMobileDemo 这份Demo吗？ 如果是这份Demo，那onPreviewResult 回传的数据格式是NV21数据格式，目前我们这边离线人脸识别就是使用的这份preview回调数据

**Comment by lanyuqingri** [comment]
咱们这边使用YuvImage 转换保存的图片的关键代码能否贴一下？ 另外传递的参数也告知一下，我们看看是否是传递参数或者调用上的问题？

**Comment by mxmjerry** [comment]
> 咱们这边使用YuvImage 转换保存的图片的关键代码能否贴一下？ 另外传递的参数也告知一下，我们看看是否是传递参数或者调用上的问题？

解决了，是传入的预览的宽高不对。需要使用这个才行 UVCCameraHelper.getInstance().getPreviewWidth()

**Comment by lanyuqingri** [comment]
OK,那此issue 先close掉了，谢谢~
