### ISSUE TITLE
使用USB相机一段时间之后，相机断流问题

### ISSUE THREAD

**Issue by dashewan11111** [RokidGlass/glass2-docs#86]
前提条件：黑盒子使用外置USB相机，OTG口插手机给手机供电。此时相机二十分钟～四十分钟后会断流。
如果此时把手机拔掉，插入电脑，给黑盒子供电。相机视频流会继续。

因为我们的使用场景是尽可能的隐蔽拍摄，不能带着rokid眼镜。所以这种情况我们有没有什么方案？

**Comment by shiwf** [comment]
请在相机App里加一个屏幕常亮锁试一下

**Comment by dashewan11111** [comment]
> 请在相机App里加一个屏幕常亮锁试一下

最新发现，确实像是手机锁屏那种整个应用暂停了。但是开启屏幕常亮并不是特别管用。只是让App运行时间变长了。后面还是会有整个App 暂停那种现象。而且插上电脑，用Vysor打开，按钮可以点击，但 是点击无效果。

**Comment by dashewan11111** [comment]
不知道跟 黑盒子剩余电量有没有关系。感觉电量越小，App 能持续运行的时间越短
