### ISSUE TITLE
Error when building UVCCameraProDemoLTS-v5.02.200071002

### ISSUE THREAD

**Issue by ljieyao** [RokidGlass/glass2-docs#87]
* What went wrong:
Execution failed for task ':libuvccamera:ndkBuild'.
> Process 'command '/usr/local/Caskroom/android-ndk/21/android-ndk-r21/ndk-build'' finished with non-zero exit value 2

does it have to use android-ndk-r11b which is originally in the zip file?

**Comment by PuppiesMeat** [comment]
you can use android-ndk-r16b
