### ISSUE TITLE
眼镜里自带的扫码如何回调

### ISSUE THREAD

**Issue by zhufeixiang** [RokidGlass/glass2-docs#88]

**Comment by sunchaonew** [comment]
这部分是扫一扫自身的功能，没有形成对外的接口，使用的话可以用  startactivityforresult 打开com.rokid.glass.scan2/com.rokid.glass.scan2.activity.QrCodeActivity  界面从com.blikoon.qrcodescanner.got_qr_scan_relult字段取参数
