### ISSUE TITLE
特征值比对

### ISSUE THREAD

**Issue by litianlue** [RokidGlass/glass2-docs#89]
没有特征值比对，如何判别该照片已经被注册了？

**Comment by lanyuqingri** [comment]
没有太明白您这边的问题，您是将图片添加到离线特征库之后，想要判断该图片是否已经添加成功？

**Comment by litianlue** [comment]
就是我这张图片已经添加，我重新再拍一张图片，如果再添加时需要判断这个特征已经加入到离线库了，所以需要比对一下这个库是否已经存在该特征，如果存在就不能增加

**Comment by lanyuqingri** [comment]
即便是同一个人在先后相同环境下拍的照片，程序这边在提取特征时也是会有细微差异的，您这边想要实现的功能是怎样的？ 场景上来说，我们是支持同一个人添加多张图片作为底库图的，这样业务逻辑上匹配这个人的准确度也就越高。

**Comment by litianlue** [comment]
如果是同一张？是不是会占用更多特征库？还有一个问题想了解一下，好像没有看到有静默活体检测的方法？

**Comment by lanyuqingri** [comment]
目前SDK还没有提供活体检测的功能，另外至于是否是同一张图片做的特征提取，我理解可以通过上层逻辑来做处理，比如已添加特征的图片路径都存放在一个数据库中，下次进来时查看数据库来判断是否已经使用过本张图片做过特征提取。

**Comment by litianlue** [comment]
假设图片都是网络下载不报存本地进行注册，那么没有特征对比方法，就会有一种现象，两个特征比较相似的人识别，会形成一种误识别的情况，如果有特征比对，那么应用层本应该不让特征相同的人再进行注册。这样也是可以避免一些问题

**Comment by lanyuqingri** [comment]
目前暂无这样的接口可以提供，您这边可以先按之前提供的建议，应用层判断网络url 或者 本地图片路径的方式先过滤一层，虽然这样做不够严谨，但目前来看也是能解决您问题的最好方式了，后续我们这边考虑一下如何增加一个这样的接口。

**Comment by litianlue** [comment]
好的

**Comment by litianlue** [comment]
如果做人证核对的话应该也实现不了吧？就是人脸和身份证核对

**Comment by lanyuqingri** [comment]
身份证识别目前暂时还没有SDK可以提供。
