### ISSUE TITLE
关于摄像头对焦问题

### ISSUE THREAD

**Issue by lh414035210** [RokidGlass/glass2-docs#90]
![image](https://user-images.githubusercontent.com/24253339/102046013-5e2a5500-3e15-11eb-8196-78a71b986101.png)

这是我对焦的效果，但是找贵公司的李经理说，可能是需要升级下硬件系统， 我们这个眼镜是三个月前买的。一直没有更新过！

**Comment by lh414035210** [comment]
![image](https://user-images.githubusercontent.com/24253339/102046206-cda04480-3e15-11eb-9b7c-6a7001417cee.png)

**Comment by lh414035210** [comment]
我这边也用手机摄像头，和Rokid   对比了下！   手机摄像头是OK的， 但是Rokid 就看不清上面的文字内容！

**Comment by Machaojoy** [comment]
> 我这边也用手机摄像头，和Rokid 对比了下！ 手机摄像头是OK的， 但是Rokid 就看不清上面的文字内容！

Hi 确认两个问题：

**Comment by Machaojoy** [comment]
> 我这边也用手机摄像头，和Rokid 对比了下！ 手机摄像头是OK的， 但是Rokid 就看不清上面的文字内容！

Hi 确认两个问题：
1. 升级眼镜的系统：Dock配网完成后，接眼镜的系统也可以更新camera的固件。或者通过“我的相机”拍相同的场景，看看AF是否有问题。
2. 应用：有没有打开AF的自动对焦。
3. 我让销售转发了一个USBcamera的测试工具，可以通过右上角打开AF功能，排查下眼镜问题还是应用问题。
