### ISSUE TITLE
眼镜IMU相关

### ISSUE THREAD

**Issue by CFHGGH** [RokidGlass/glass2-docs#93]
系统版本1.1.1-20201202-202102
ui版本 1.5.6 imu 1.3.8 这个版本适配不上
在适配添加点击事件  触控板单击相应的不是当前位置 （使用投屏工具触摸交互响应位置正确）

**Comment by sunchaonew** [comment]
你好，最新版本的glassuisdk升级版本到了1.6.0，已经修复了此问题，可以升级glassui版本再验证下
