### ISSUE TITLE
implementation 'com.rokid.alliance.usbcamera:usbcamera:1.1.9'

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#96]
引入这个包  程序无法运行，提示Cause: connect timed out   如何解决

**Comment by PuppiesMeat** [comment]
@kaojin-alt 麻烦提供更为详细的错误输出

**Comment by kaojin-alt** [comment]
错误输入只有这个

**Comment by PuppiesMeat** [comment]
是无法下载包吗？

**Comment by kaojin-alt** [comment]
Executing tasks: [:phone_app:assembleIim_phone_devDebug] in project /Users/apple/Documents/android_studio_workspace/iim


> Configure project :common
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :phone_app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Task spend time:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':phone_app:processIim_phone_devDebugResources'.
> Could not resolve all task dependencies for configuration ':phone_app:iim_phone_devDebugRuntimeClasspath'.
   > Could not resolve com.rokid.alliance.usbcamera:usbcamera:1.1.9.
     Required by:
         project :phone_app > project :glasses_rokid
      > Could not resolve com.rokid.alliance.usbcamera:usbcamera:1.1.9.
         > Could not get resource 'https://maven.google.com/com/rokid/alliance/usbcamera/usbcamera/1.1.9/usbcamera-1.1.9.pom'.
            > Could not HEAD 'https://maven.google.com/com/rokid/alliance/usbcamera/usbcamera/1.1.9/usbcamera-1.1.9.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.200.78] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s

**Comment by kaojin-alt** [comment]
应该是包一直下载不下来

**Comment by PuppiesMeat** [comment]
参考文档配置gradle https://rokidglass.github.io/glass2-docs/zh/7-glassmobile/res/mobile_glass/glass_hardware.html

**Comment by kaojin-alt** [comment]
都配置过了

**Comment by PuppiesMeat** [comment]
project :phone_app > project :glasses_rokid
> Could not resolve com.rokid.alliance.usbcamera:usbcamera:1.1.9.
> Could not get resource 'https://maven.google.com/com/rokid/alliance/usbcamera/usbcamera/1.1.9/usbcamera-1.1.9.pom'.
> Could not HEAD 'https://maven.google.com/com/rokid/alliance/usbcamera/usbcamera/1.1.9/usbcamera-1.1.9.pom'.
> Connect to maven.google.com:443 [maven.google.com/216.58.200.78] failed: Read timed out

你的maven都是在 https://maven.google.com去拉取 明显没有按照文档配置

**Comment by PuppiesMeat** [comment]
在根目录build.gradle文件配置
allprojects {
             repositories {
                 maven { url = 'https://dl.bintray.com/rokid/alliance/' }
             }
     }
