### ISSUE TITLE
RKGlassDevice

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#98]
RKGlassDevice.RKGlassDeviceBuilder.buildRKGlassDevice().build().initUsbDevice();
获取usb权限只能通过这个方法吗？

**Comment by zhangshengwei** [comment]
目前我们SDK只提供了这个方法，咋们现在通过这个方法去获取usb权限有什么问题吗？

**Comment by zhangshengwei** [comment]
> RKGlassDevice.RKGlassDeviceBuilder.buildRKGlassDevice().build().initUsbDevice();
> 获取usb权限只能通过这个方法吗？

目前我们SDK只提供了这个方法，咋们现在通过这个方法去获取usb权限有什么问题吗？

**Comment by kaojin-alt** [comment]
这个方法需要传入一个视频view   我现在只想取得usb权限  还不需要显示视频view

**Comment by kaojin-alt** [comment]
如果只有这一个方法，无法将usb权限与视频view分开，而且获取视频画面   没有注销的方法

**Comment by zhangshengwei** [comment]
> 这个方法需要传入一个视频view 我现在只想取得usb权限 还不需要显示视频view

咋们可以将视频的view的大小尺寸设置为1像素的；

咋们也可以找一些三方的库去获取usb的权限
