### ISSUE TITLE
关于屏幕录制

### ISSUE THREAD

**Issue by kaojin-alt** [RokidGlass/glass2-docs#99]
自己开发了一个app 有播放视频的功能，在播放视频时，使用眼镜自带的录屏功能无法将视屏内容录制下来
怎么解决

**Comment by shiwf** [comment]
您好，播放视频时如果使用SurfaceView，则录屏时无法将视频内容录制下来。要录屏时录到视频内容，需使用TextureView来播放视频内容。

**Comment by kaojin-alt** [comment]
我用的videoview

**Comment by shiwf** [comment]
> 我用的videoview也不行吗

VideoView就是SurfaceView的封装，也是不可以的。想要录屏录下来，只能使用TextureView
